Transaction Exempt
0chain/0chain pull request #1012
Opened 2022-02-19 17:59 UTC by ssardana08

Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/0chain/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master BEFORE merging this PR  
  
Associated PRs (Link as appropriate):
...

2022-02-20 17:11 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | feat/exempt_transaction  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-02-21 14:51 UTC, Sriep commented on code/go/0chain.net/chaincore/transaction/entity.go
> +//}
You can delete this comment now. Moved to 0chain.yaml.

2022-02-21 14:54 UTC, Sriep requested changes, later dismissed
Looks ok for the moment. We might need to modify later to handle duplicate function names.

Integration testing.
1. To start just test global-config and global-update-config. So your not testing the fee-charging bit, just that the setting can be changed and is integrated correctly.
2. Next we need a way of eyeballing exempt fee in action. Maybe try to not give yourself enough tokens to pay for the transactions. And check you fail at the correct time.

2022-02-21 14:54 UTC, Sriep commented on code/go/0chain.net/chaincore/transaction/entity.go
> +//}
You can delete this now, moved to 0chain.yaml.

2022-02-22 14:54 UTC, ssardana08 reviewed
tested and verified

2022-02-22 15:39 UTC, ssardana08 commented
> Looks ok for the moment. We might need to modify later to handle duplicate function names.
> 
> Integration testing.
> 
> 1. To start just test global-config and global-update-config. So your not testing the fee-charging bit, just that the setting can be changed and is integrated correctly.
> 2. Next we need a way of eyeballing exempt fee in action. Maybe try to not give yourself enough tokens to pay for the transactions. And check you fail at the correct time.

done

2022-02-22 15:59 UTC, ssardana08 reviewed
done

2022-02-22 19:53 UTC, Sriep approved these changes

2022-02-22 19:59 UTC, merged