Benchmark test improvments
0chain/0chain pull request #1067
Opened 2022-03-18 17:14 UTC by Sriep

## Changes
Makes using large MPT databases easier

1. Use parallel processing to generate the simulation database.
2. Reuse the MPT database with the new load and save options.

## Fixes

## Tests 
Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/0chain/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

## Associated PRs (Link as appropriate):
- blobber:
- gosdk:
- system_test:
- zboxcli:
- zwalletcli:
- Other: ...

2022-03-22 23:26 UTC, peterlimg requested changes

2022-03-22 23:26 UTC, peterlimg commented on code/go/0chain.net/chaincore/threshold/bls/dkg_entity_gen.go
> +	"github.com/dchenk/msgp/msgp"
Seems like used wrong msgp package

2022-03-22 23:26 UTC, peterlimg commented on code/go/0chain.net/go.mod
> +	github.com/dchenk/msgp/msgp v0.0.0-20180815194337-5c34657c2259 // indirect
Seems like used wrong package

2022-03-26 08:31 UTC, Sriep commented on code/go/0chain.net/chaincore/threshold/bls/dkg_entity_gen.go
> +	"github.com/dchenk/msgp/msgp"
This fixed itself when I ran `make mgsp`.

2022-03-28 05:30 UTC, peterlimg submitted a review, later dismissed
lgtm

2022-03-28 11:24 UTC, peterlimg approved these changes

2022-03-28 13:31 UTC, merged