changed json parsing
0chain/0chain pull request #1068
Opened 2022-03-18 23:31 UTC by samtholiya

## Changes

## Fixes

## Tests 
Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/0chain/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

## Associated PRs (Link as appropriate):
- blobber:
- gosdk:
- system_test:
- zboxcli:
- zwalletcli:
- Other: ...

2022-03-27 11:06 UTC, peterlimg requested changes
Is this PR ready or still working in progress?

2022-03-27 11:06 UTC, peterlimg commented on code/go/0chain.net/smartcontract/storagesc/models.go
> +	PreferredBlobbers []string                      `json:"blobbers"`
Please change the `PreferredBlobbers` too

2022-03-27 22:10 UTC, ma2b0043 commented
@samtholiya @peterlimg when can we expect to close this PR?

2022-03-29 13:22 UTC, samtholiya commented
This pr is not needed so closing this pr

2022-03-29 13:22 UTC, closed without merging