Stop generating challenges is there are no validators
0chain/0chain pull request #1080
Opened 2022-03-26 09:24 UTC by Kishan-Dhakan

## Changes

## Fixes

## Tests 
Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/0chain/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

## Associated PRs (Link as appropriate):
- blobber:
- gosdk:
- system_test:
- zboxcli:
- zwalletcli:
- Other: ...

2022-03-26 21:22 UTC, service-0chain commented
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | enhance/challenge-generation-no-validator  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-03-27 01:35 UTC, peterlimg requested changes

2022-03-27 01:35 UTC, peterlimg commented on .github/workflows/system_tests.yml
> +    uses: 0chain/actions/.github/workflows/manual_system_tests.yml@check-without-validators
Do not change this, we can select this branch by running system test manually

2022-03-27 21:53 UTC, ma2b0043 commented
@Kishan-Dhakan @peterlimg when can we expect to close this PR?

2022-03-28 02:50 UTC, peterlimg approved these changes
lgtm

2022-03-28 07:46 UTC, merged

2022-03-28 07:46 UTC, Kishan-Dhakan commented
> @Kishan-Dhakan @peterlimg when can we expect to close this PR?

Was awaiting some reviews, done @ma2b0043 👍