Fix #1077 update blobber stake
0chain/0chain pull request #1129
Opened 2022-04-04 22:04 UTC by samtholiya

## Changes

## Fixes

## Tests 
Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/0chain/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

## Associated PRs (Link as appropriate):
- blobber:
- gosdk:https://github.com/0chain/gosdk/pull/421
- system_test:
- zboxcli:https://github.com/0chain/zboxcli/pull/203
- zwalletcli:
- Other: ...

2022-04-04 22:06 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | totalstakeBlobber  |
| zboxcli  | displaytotalstake  |
| zwalletcli  | staging  |
| 0chain  | totalstakeblobber  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-04-04 22:50 UTC, service-0chain commented
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | totalstakeBlobber  |
| zboxcli  | displaytotalstake  |
| zwalletcli  | staging  |
| 0chain  | totalstakeblobber  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-04-05 00:01 UTC, peterlimg requested changes

2022-04-05 00:01 UTC, peterlimg commented on code/go/0chain.net/smartcontract/storagesc/allocation.go
> +		data, _ := json.Marshal(dbs.DbUpdates{
Please check the error and report if any, otherwise empty data could be insert to event db and we don't know what happen. So as the other places below.

2022-04-05 00:01 UTC, peterlimg commented on code/go/0chain.net/smartcontract/storagesc/allocation.go
> +				"total_stake": int64(sps[1].stake()),
`sps[1]` - > `sps[i]`

2022-04-05 19:36 UTC, samtholiya commented on code/go/0chain.net/smartcontract/storagesc/allocation.go
> +		data, _ := json.Marshal(dbs.DbUpdates{
empty data still does not give an error.

2022-04-05 19:39 UTC, samtholiya commented on code/go/0chain.net/smartcontract/storagesc/allocation.go
> +				"total_stake": int64(sps[1].stake()),
done

2022-04-05 19:40 UTC, samtholiya commented on code/go/0chain.net/smartcontract/storagesc/allocation.go
> +		data, _ := json.Marshal(dbs.DbUpdates{
The error is given only when there is a cyclic graph in the data structure or some manual interface fails. As there is none for sure in the above case we can avoid it.

2022-04-06 11:17 UTC, peterlimg approved these changes
lgtm

2022-04-06 13:26 UTC, merged