Partition refactoring
0chain/0chain pull request #1143
Opened 2022-04-11 06:27 UTC by peterlimg

## Fixes

## Changes

TLDR:
- Make it easy to support new partitions
- Clean APIs
- Move partition data types to their own packages
- Fixed the `GetRandomSlice()` bug
- Performance improvements
- Check [README](https://github.com/0chain/0chain/commit/09f8654481f255027e7c4c87ffd734aeccb6120f) for the details about how to use the partition package.

### Purpose
The purpose of this PR was to make the partition easy to use and easy to support new partitions, check issue #1142 for details. 

After refactoring, the `partitions` package is a pure utility package, hence no business data structs defined there. 

Main APIs are:

```go
// Create partitions if not exists
func CreateIfNotExists(state state.StateContextI, name string, size int) (*Partitions, error)

// Get partitions of given name
func GetPartitions(state state.StateContextI, name string) (*Partitions, error)

// Get random items from given partitions, the items will be returned through the last parameter
func GetRandomItems(state state.StateContextI, name string, v interface{}) error

// Get item from given partition index and item id
func (p *Partitions) GetItem(state state.StateContextI, partIndex int, id string, v interface{}) error

// Update item in given partition
func (p *Partitions) UpdateItem(state state.StateContextI, partIndex int, item PartitionItem) error

// Save saves the partitions to MPT
func (p *Partitions) Save(state state.StateContextI) error
...
```

### Unexpected performance gain
Apart from the main purpose for making the package easy to use, the performance was also improved especially the `GetItem()` method. Previously if we want to get an item from partition, we will need to decode all the items in the partition and go through the item list to find it. But now, we don't need to decode every pieces of struct fields of each item, instead we only decode the `ID` field as an index, and the remaining data are kept as `[]byte`, so only when we find the `ID` is matched, we will decode the `[]byte` into concrete type. The new `GetItem()` methods is about 20~30x faster than before if the previous way code is written correctly(i.e, use interface assert instead calling `Decode(data.Encode())` to get item), or it would be even faster.
  -  The `GetRandomItems()` (previously as `GetRandomSlice()`) is slightly faster, but since we are using reflection partially to make this API clean, I didn't expect it could be faster than the previous version, but yeah the truths is, it is faster indeed.
  - The `UpdateItem()` is also faster than before apparently, as finding the item is faster.
  - I believe remove item would be faster as well, because we don't need to decode the full item list to find the item to remove. 

## Tests 
Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/0chain/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

## Associated PRs (Link as appropriate):
No

2022-04-11 12:09 UTC, dabasov approved these changes
lgtm

2022-04-11 17:08 UTC, ssardana08 requested changes

2022-04-11 17:08 UTC, ssardana96 commented on code/go/0chain.net/smartcontract/partitions/partitions.go
> +	rp *randomSelector
would rs be a better name here?

2022-04-11 17:08 UTC, ssardana96 commented on code/go/0chain.net/smartcontract/partitions/partitions.go
> +func CreateIfNotExists(state state.StateContextI, name string, partitionSize int) (*Partitions, error) {
it can call GetPartitions

2022-04-11 17:08 UTC, ssardana96 commented on code/go/0chain.net/smartcontract/partitions/partitions.go
> +// Partitioner interface wraps the methods for processing a partition
we can remove this

2022-04-11 17:08 UTC, ssardana96 commented on code/go/0chain.net/smartcontract/partitions/random.go
> +		part, err = rs.getPartition(state, len(rs.Partitions)-1)
state looks like a better name than balances.
I guess we should change everywhere to state

2022-04-11 17:08 UTC, ssardana96 commented on code/go/0chain.net/smartcontract/storagesc/blobber_reward_partition.go
> +	c_state "0chain.net/chaincore/chain/state"
we should think of better name to distinguish them?
can chaincore/chain/state be moved to chaincore/state only?

2022-04-12 23:47 UTC, peterlimg commented on code/go/0chain.net/smartcontract/partitions/partitions.go
> +func CreateIfNotExists(state state.StateContextI, name string, partitionSize int) (*Partitions, error) {
We have `GetPartitions()` function, and `Get*` function should not have `update` action

2022-04-12 23:49 UTC, peterlimg commented on code/go/0chain.net/smartcontract/partitions/random.go
> +		part, err = rs.getPartition(state, len(rs.Partitions)-1)
Yes, but the name is conflict with the `state` package, so perhaps we need another better name. Anyway, I'll keep it here and think about it later.

2022-04-12 23:53 UTC, peterlimg commented on code/go/0chain.net/smartcontract/storagesc/blobber_reward_partition.go
> +	c_state "0chain.net/chaincore/chain/state"
They are two difference thing, but yes, we need to think of a better package name. We can do it later perhaps

2022-04-14 13:18 UTC, sum-it08 approved these changes

2022-04-17 02:03 UTC, merged