ChangeBlobber unit test
0chain/0chain pull request #1217
Opened 2022-04-29 14:36 UTC by sum-it08

## Changes
- Unit test for changeBlobber
- Unit test for removeBlobber
- Fix removeBlobber logical error

## Fixes

## Tests 
Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/0chain/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

## Associated PRs (Link as appropriate):
- blobber:
- gosdk:
- system_test:
- zboxcli:
- zwalletcli:
- Other: ...

2022-05-01 08:56 UTC, Sriep commented on code/go/0chain.net/smartcontract/storagesc/allocation_test.go
> +		//balances.On("EmitEvent", event.TypeStats, event.TagUpdateBlobber, mock.Anything, mock.Anything).Return()
Remove comment

2022-05-01 08:56 UTC, Sriep commented on code/go/0chain.net/smartcontract/storagesc/models.go
> +	//}
Remove commented-out code.

2022-05-02 01:15 UTC, peterlimg requested changes

2022-05-02 01:15 UTC, peterlimg commented on code/go/0chain.net/smartcontract/storagesc/allocation_test.go
> +			}},
Please add more test cases, we should cover most of the process logic of the changeBlobbers method.

2022-05-02 01:15 UTC, peterlimg commented on code/go/0chain.net/smartcontract/storagesc/allocation_test.go
> +			name: "test_blobber_remove_doesnt_exist",
We don't need the `test_` prefix of the name

2022-05-02 01:15 UTC, peterlimg commented on code/go/0chain.net/smartcontract/storagesc/allocation_test.go
> +			require.EqualValues(t, tt.want.err, err != nil)
Please assert the state as well, if we removed a blobber, please check and assert the blobber is removed, and related state were updated correctly. Checking the error message is literally useless, we need to check if the state is changed as we expected.

2022-05-05 15:45 UTC, Sriep approved these changes

2022-05-06 13:03 UTC, peterlimg approved these changes
lgtm

2022-05-07 12:06 UTC, merged

2022-05-07 14:27 UTC, service-0chain commented
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | master  |
| 0proxy  | staging  |
| 0search  | staging  |