WIP Remaster `blobber_test_go`, `Test_flow_reward`
0chain/0chain pull request #122
Opened 2021-03-21 12:11 UTC by Sriep

[Test_flow_reward ](https://github.com/0chain/0chain/blob/master/code/go/0chain.net/smartcontract/storagesc/blobber_test.go#L129) unit test is bugged. The golang `testing` package can't seem to handle the [testBalances](https://github.com/0chain/0chain/blob/master/code/go/0chain.net/smartcontract/storagesc/balances_test.go#L19) object; In that, it fails to reset the object between `t.Run` calls. Resulting in corrupted data. 

This PR handles the fees and rewards testing by lifting the formulae used into a separate `formulae` object, where they can be examined.

2021-03-25 11:54 UTC, kirillt approved these changes
Looks good overall. Please also look at minor comments.

2021-03-25 13:11 UTC, Sriep commented on code/go/0chain.net/smartcontract/storagesc/formulae_test.go
> +package storagesc
You don't want test files slowing down `go build`. `_test` are automatically omitted from `go build` don't think `test_....go` files are. You could add a `\\ build test` tag but that's complicated. You can have a `testing` subdirectory I think files there are ignored by `go build`.

2021-03-25 23:21 UTC, kirillt commented on code/go/0chain.net/smartcontract/storagesc/formulae_test.go
> +package storagesc
Ooh, ok, I thought Go resolves compilation dependencies and skips everything what is not called from main, by default.
`testing` subdirectory sounds good.

2021-04-19 04:30 UTC, peterlimg requested changes
I see commits for reverting the changes that added by @kirillt, those changes should have already been reverted on master branch. Would you mind to do a rebase from master, thanks.

2021-04-19 04:30 UTC, peterlimg commented on code/go/0chain.net/smartcontract/minersc/READEME.md
> +interest_rewrds (mint) = stake_capacity * interest_rate
Is the `rewrds` a typo ?

2021-05-03 13:36 UTC, Sriep commented
Needs reworking due to recent bug fixes, for example https://github.com/0chain/0chain/pull/182 and https://github.com/0chain/0chain/pull/217. Also, overlap with https://github.com/0chain/0chain/pull/174. 

Moved to Issue https://github.com/0chain/0chain/issues/130.

2021-05-03 13:36 UTC, closed without merging