Refactor swagger rest api changes
0chain/0chain pull request #1304
Opened 2022-05-25 11:02 UTC by Sriep

## Fixes
Refactor of rest api for reivew issues raised in https://github.com/0chain/0chain/pull/1134
## Changes

## Need to be mentioned in CHANGELOG.md?

## Tests
Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/0chain/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

## Associated PRs (Link as appropriate):
- blobber:
- gosdk:
- system_test:
- zboxcli:
- zwalletcli:
- Other: ...

2022-05-25 13:25 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | swagger  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | restapi_refactor  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-05-26 11:38 UTC, service-0chain commented
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | restapi_refactor  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | master  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-05-26 13:49 UTC, service-0chain commented
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | swagger  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | restapi_refactor  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-05-26 14:17 UTC, peterlimg requested changes

2022-05-26 14:17 UTC, peterlimg commented on code/go/0chain.net/smartcontract/minersc/handler.go
> +		{Name: miner + "/globalSettings", Endpoint: mrh.getGlobalSettings},
Perhaps we can have a function in `rest` package to construct the `RestEndpoint` instance. Such as: MakeEndpoint(miner, "/globalSettings", mrh.getGlobalSettings). So the code will be like:

```go
return []rest.RestEndpoint {
   rest.MakeEndpoint(miner+"/globalSettings", mrh.getGlobalSettings),
  rest.MakeEndpoint(miner+"/getNodepool", mrh.getNodePool),
....
}
```

2022-05-26 14:17 UTC, peterlimg commented on code/go/0chain.net/smartcontract/rest/rest.go
> +type RestEndpoint struct {
Since the package name is rest, so we can rename this struct to `Endpoint` to reduce repetition.

2022-05-26 14:17 UTC, peterlimg commented on code/go/0chain.net/smartcontract/rest/rest.go
> +	Endpoint func(w http.ResponseWriter, r *http.Request)
Name -> URI, Endpoint -> Handler might be better

2022-05-27 11:26 UTC, peterlimg approved these changes
lgtm

2022-05-27 11:44 UTC, merged

2022-05-28 10:54 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | master  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-05-28 11:46 UTC, service-0chain commented
Manual system tests [cancelled] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | master  |
| 0proxy  | staging  |
| 0search  | staging  |