Remove blobber pools
0chain/0chain pull request #1313
Opened 2022-05-27 09:44 UTC by Sriep

## Fixes
Removes blobber pools from allocation pools.
## Changes

## Need to be mentioned in CHANGELOG.md?

## Tests
Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/0chain/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

## Associated PRs (Link as appropriate):
- blobber:
- gosdk: https://github.com/0chain/system_test/pull/279
- system_test: https://github.com/0chain/system_test/pull/279
- zboxcli:
- zwalletcli:
- Other: ...
- Replaces https://github.com/0chain/0chain/pull/1311.

2022-05-27 11:37 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | remove_bloober_pools  |
| gosdk  | remove_blobber_pools  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | blobber_pools  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-05-27 12:28 UTC, peterlimg requested changes

2022-05-27 12:28 UTC, peterlimg commented on code/go/0chain.net/smartcontract/storagesc/allocation_pool_test.go
> +	"0chain.net/chaincore/tokenpool"
Seems not formatted, please run goimports to format

2022-05-27 12:28 UTC, peterlimg commented on code/go/0chain.net/smartcontract/storagesc/readpool.go
>  			move currency.Coin
We'd better not use var block for single variable

2022-05-27 12:34 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | remove_bloober_pools  |
| gosdk  | remove_blobber_pools  |
| zboxcli  | blobber_pools  |
| zwalletcli  | staging  |
| 0chain  | blobber_pools  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-05-31 01:31 UTC, peterlimg approved these changes
lgtm, please fix the system test errors

2022-06-21 08:26 UTC, Sriep commented
Replaced with https://github.com/0chain/0chain/pull/1373

2022-06-21 08:26 UTC, closed without merging