- removing allocation from blobberAllocPartition on finishAllocation
0chain/0chain pull request #1386
Opened 2022-06-14 13:43 UTC by sum-it08

## Fixes

## Changes

## Need to be mentioned in CHANGELOG.md?

## Tests
Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/0chain/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

## Associated PRs (Link as appropriate):
- blobber:
- gosdk:
- system_test:
- zboxcli:
- zwalletcli:
- Other: ...

2022-06-15 01:31 UTC, peterlimg requested changes

2022-06-15 01:31 UTC, peterlimg commented on code/go/0chain.net/smartcontract/storagesc/allocation.go
> +		err = removeAllocationFromBlobber(sc, d.BlobberID, d.BlobberAllocationsPartitionLoc, alloc.ID, balances)
We can do group removing by getting all blobbers that have the same partition location and remove them in one parititon read/write.

2022-06-15 14:13 UTC, ssardana08 commented on code/go/0chain.net/smartcontract/storagesc/allocation.go
> +		err = removeAllocationFromBlobber(sc, d.BlobberID, d.BlobberAllocationsPartitionLoc, alloc.ID, balances)
anyhow that won't make a difference.. because blobberAllocation is fetched for each and every blobber.
they all are in different partition altogether. Check `removeAllocationFromBlobber`

2022-06-16 00:37 UTC, peterlimg commented on code/go/0chain.net/smartcontract/storagesc/allocation.go
> +		err = removeAllocationFromBlobber(sc, d.BlobberID, d.BlobberAllocationsPartitionLoc, alloc.ID, balances)
oh yes, you right. They are in different partitions.

2022-06-16 00:37 UTC, peterlimg approved these changes
lgtm

2022-06-16 00:37 UTC, merged