Feat/allocation storage per period
0chain/0chain pull request #1394
Opened 2022-06-16 08:26 UTC by lawRathod

## Fixes

## Changes
Closes https://github.com/0chain/0chain/issues/1367

## Need to be mentioned in CHANGELOG.md?

## Tests
Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/0chain/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

## Associated PRs (Link as appropriate):
- blobber:
- gosdk:
- system_test:
- zboxcli:
- zwalletcli:
- Other: ...

2022-06-17 17:35 UTC, dabasov requested changes

2022-06-17 17:35 UTC, dabasov commented on code/go/0chain.net/smartcontract/dbs/event/writemarker.go
> +		Where("block_number > ? AND block_number < ?", startBlockNum, endBlockNum).
add index to table

2022-06-18 01:04 UTC, peterlimg requested changes, later dismissed

2022-06-18 01:04 UTC, peterlimg commented on code/go/0chain.net/smartcontract/storagesc/handler.go
> +		rest.MakeEndpoint(storage+"/allocWrittenSizePerPeriod", srh.getWrittenAmountPerPeriod),
Change to `/alloc-written-size-per-period`

2022-06-19 10:44 UTC, lawRathod commented on code/go/0chain.net/smartcontract/dbs/event/writemarker.go
> +		Where("block_number > ? AND block_number < ?", startBlockNum, endBlockNum).
Done

2022-06-22 11:50 UTC, dabasov approved these changes
lgtm

2022-06-24 14:38 UTC, merged