Feat/get txn hashes
0chain/0chain pull request #1396
Opened 2022-06-17 07:30 UTC by lawRathod

## Fixes

## Changes
Closes https://github.com/0chain/0chain/issues/1365

## Need to be mentioned in CHANGELOG.md?

## Tests
Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/0chain/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

## Associated PRs (Link as appropriate):
- blobber:
- gosdk:
- system_test:
- zboxcli:
- zwalletcli:
- Other: ...

2022-06-17 17:30 UTC, dabasov requested changes

2022-06-17 17:30 UTC, dabasov commented on code/go/0chain.net/smartcontract/storagesc/handler.go
> +		contentHash  = r.URL.Query().Get("content_hash")
use common API here after benchmark merge

2022-06-17 17:30 UTC, dabasov commented on code/go/0chain.net/smartcontract/storagesc/handler.go
> +		lookUpHash   = r.URL.Query().Get("look_up_hash")
add index to WriteMarker

2022-06-17 17:30 UTC, dabasov commented on code/go/0chain.net/smartcontract/storagesc/handler.go
> +		name         = r.URL.Query().Get("name")
Add index to WriteMarker

2022-06-18 01:02 UTC, peterlimg requested changes, later dismissed

2022-06-18 01:02 UTC, peterlimg commented on code/go/0chain.net/smartcontract/storagesc/handler.go
> +		rest.MakeEndpoint(storage+"/transactionHashes", srh.getTransactionHashesByFilter),
let's use hyphen for URI, so `transaction-hashes`

2022-06-18 01:02 UTC, peterlimg commented on code/go/0chain.net/smartcontract/storagesc/handler.go
> +//    + name: content_hash
use hyphen `-` instead of underscore `_`, we will need to apply this for all URIs.

2022-06-18 13:08 UTC, dabasov commented
please add benchmark

2022-06-19 08:56 UTC, lawRathod commented on code/go/0chain.net/smartcontract/storagesc/handler.go
> +		lookUpHash   = r.URL.Query().Get("look_up_hash")
Done

2022-06-19 08:56 UTC, lawRathod commented on code/go/0chain.net/smartcontract/storagesc/handler.go
> +		contentHash  = r.URL.Query().Get("content_hash")
Done

2022-06-19 08:56 UTC, lawRathod commented on code/go/0chain.net/smartcontract/storagesc/handler.go
> +		name         = r.URL.Query().Get("name")
Done

2022-06-22 11:48 UTC, dabasov requested changes

2022-06-22 11:48 UTC, dabasov commented on code/go/0chain.net/smartcontract/dbs/event/writemarker.go
> +		Offset(limit.Offset).
add ordering

2022-06-22 11:48 UTC, dabasov commented on code/go/0chain.net/smartcontract/storagesc/benchmark_rest_tests.go
> +					"limit":        "",
leave them blank if not used

2022-06-22 11:48 UTC, dabasov commented on code/go/0chain.net/smartcontract/storagesc/handler.go
> +//    + name: limit
add ordering param

2022-06-22 15:32 UTC, lawRathod commented on code/go/0chain.net/smartcontract/storagesc/handler.go
> +//    + name: limit
Done

2022-06-22 15:32 UTC, lawRathod commented on code/go/0chain.net/smartcontract/storagesc/benchmark_rest_tests.go
> +					"limit":        "",
done

2022-06-22 15:32 UTC, lawRathod commented on code/go/0chain.net/smartcontract/dbs/event/writemarker.go
> +		Offset(limit.Offset).
done

2022-06-22 20:48 UTC, dabasov approved these changes
lgtm

2022-06-24 14:40 UTC, merged