Fix/magic block
0chain/0chain pull request #1408
Opened 2022-06-19 18:11 UTC by dabasov

## Fixes

magic-block generation is now up to date with mainnet requirements

2022-06-21 01:06 UTC, peterlimg requested changes
The zip files exist in both magicBlock/input folder and the `one` and `two` folders, should any of them be removed from the commits?

2022-06-21 01:06 UTC, peterlimg commented on code/go/0chain.net/chaincore/block/magicBlock/main.go
> +	//rootPath = "/Users/dabasov/Projects/0chain_others/magic-block/docker.local/config"
Remove the commented code

2022-06-21 01:06 UTC, peterlimg commented on docker.local/build.magicBlock/Dockerfile
> +#COPY ./code/go/0chain.net $SRC_DIR/go/0chain.net
Remove commented code

2022-06-22 14:07 UTC, dabasov commented
> The zip files exist in both magicBlock/input folder and the `one` and `two` folders, should any of them be removed from the commits?

cleaned

2022-06-28 04:05 UTC, peterlimg approved these changes
lgtm

2022-06-28 04:07 UTC, merged