Write pools
0chain/0chain pull request #1465
Opened 2022-07-05 11:49 UTC by Sriep

## Fixes

## Changes

## Need to be mentioned in CHANGELOG.md?

## Tests
Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/0chain/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

## Associated PRs (Link as appropriate):
- blobber:
- gosdk:
- system_test:
- zboxcli:
- zwalletcli:
- Other: ...

2022-07-05 12:08 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | remove/writepool  |
| gosdk  | remove_write_pools  |
| zboxcli  | remove_write_pool  |
| zwalletcli  | staging  |
| 0chain  | write_pools  |
| blobber  | remove_write_pools  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-07-07 12:35 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | remove/writepool  |
| gosdk  | remove_write_pools  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | write_pools  |
| blobber  | remove_write_pools  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-07-07 19:14 UTC, service-0chain commented
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | remove/writepool  |
| gosdk  | remove_write_pools  |
| zboxcli  | remove_write_pool  |
| zwalletcli  | staging  |
| 0chain  | write_pools  |
| blobber  | remove_write_pools  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-07-11 22:40 UTC, dabasov approved these changes
lgtm

2022-07-12 06:48 UTC, peterlimg requested changes
Good job, please check the comments, thanks.

2022-07-12 06:48 UTC, peterlimg commented on code/go/0chain.net/smartcontract/storagesc/allocation.go
> +			delta, err := currency.MinusCoin(d.MinLockDemand, d.Spent)
Seems the d.Spent also include the tokens move for readMarker, is that okay to minues the token from write pool below.

2022-07-12 06:48 UTC, peterlimg commented on code/go/0chain.net/smartcontract/storagesc/config.go
> +	WritePool *writePoolConfig `json:"allocation_pool"`
Is this pool for both write and read? if yes, we may need to rename the variable WritePool.

2022-07-12 06:48 UTC, peterlimg commented on code/go/0chain.net/smartcontract/storagesc/config_settigns.go
> +		"write_pool.min_lock",
It's writepool

2022-07-12 06:48 UTC, peterlimg commented on code/go/0chain.net/smartcontract/storagesc/config_settigns.go
> +		"write_pool.min_lock": {WritePoolMinLock, smartcontract.CurrencyCoin},
writepool

2022-07-12 06:48 UTC, peterlimg commented on code/go/0chain.net/smartcontract/storagesc/config_settings_test.go
> +					"write_pool.min_lock": "10",
writepool

2022-07-12 06:48 UTC, peterlimg commented on code/go/0chain.net/smartcontract/storagesc/models.go
> +	sa.WritePool, err = currency.AddCoin(sa.WritePool, txn.Value)
If error happens, the sa.WritePool will be set to 0, we'd better keep it unchanged in case the sa would be used somewhere even the AddCoin failed.

2022-07-12 06:48 UTC, peterlimg commented on code/go/0chain.net/smartcontract/storagesc/models.go
> +	cp.Balance, err = currency.AddCoin(cp.Balance, value)
same as the WritePool above

2022-07-12 06:48 UTC, peterlimg commented on code/go/0chain.net/smartcontract/storagesc/models.go
> +	sa.WritePool, err = currency.MinusCoin(sa.WritePool, value)
Same as above

2022-07-12 06:48 UTC, peterlimg commented on code/go/0chain.net/smartcontract/storagesc/models.go
> +	cp.Balance, err = currency.MinusCoin(cp.Balance, value)
As above

2022-07-12 06:48 UTC, peterlimg commented on code/go/0chain.net/smartcontract/storagesc/models.go
> +	sa.WritePool, err = currency.AddCoin(sa.WritePool, value)
As above

2022-07-12 06:48 UTC, peterlimg commented on code/go/0chain.net/smartcontract/storagesc/stakepool.go
> +		dp.Balance, err = currency.MinusCoin(dp.Balance, dpSlash)
Avoid changing dp.Balance directly to make the sp reusable.

2022-07-12 06:48 UTC, peterlimg commented on code/go/0chain.net/smartcontract/storagesc/stakepool.go
> +		alloc.WritePool, err = currency.AddCoin(alloc.WritePool, dpSlash)
As above

2022-07-12 06:48 UTC, peterlimg commented on code/go/0chain.net/smartcontract/storagesc/writepool.go
> +	transfer := state.NewTransfer(txn.ClientID, txn.ToClientID, currency.Coin(txn.Value))
Unnecessary currency.Coin type conversion.

2022-07-12 09:25 UTC, sum-it08 requested changes

2022-07-12 09:25 UTC, ssardana08 commented on code/go/0chain.net/smartcontract/benchmark/benchmark.go
> +	StorageWritePoolMinLock              = SmartContract + StorageSc + "write_pool.min_lock"
let's change it to writepool.min_lock to maintain uniformity with sc.yaml

2022-07-12 09:25 UTC, ssardana08 commented on code/go/0chain.net/smartcontract/benchmark/main/config/benchmark.yaml
> +    write_pool:
to maintain uniformity with sc.yaml, we should keep name same
`writepool`

2022-07-12 09:25 UTC, ssardana08 commented on code/go/0chain.net/smartcontract/benchmark/main/config/benchmark.yaml
> +    max_pools_per_allocation: 10
is this being used anywhere?

2022-07-12 09:25 UTC, ssardana08 commented on code/go/0chain.net/smartcontract/storagesc/alloation2_test.go
> +	val *= wp
better to use `currency.MultCoin`

2022-07-12 09:25 UTC, ssardana08 commented on code/go/0chain.net/smartcontract/storagesc/benchmark_tests.go
> +				Value:        currency.Coin(100 * viper.GetUint64(bk.StorageMaxWritePrice) * 1e10),
if any error, we should use currency.ParseZCN()

2022-07-12 11:15 UTC, Sriep commented on code/go/0chain.net/smartcontract/storagesc/allocation.go
> +			delta, err := currency.MinusCoin(d.MinLockDemand, d.Spent)
Maybe but this is the [exsiting code ](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/storagesc/allocation.go#L1594)
```go
		var paid currency.Coin
		lack := d.MinLockDemand - d.Spent
		if d.MinLockDemand > d.Spent {
```
Also, as part of the new cancellation charge https://github.com/0chain/0chain/issues/1405 all the min lock demand code will be removed. So I don't think this is the place to fix this.

2022-07-12 16:18 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | remove_write_pools  |
| zboxcli  | remove_write_pool  |
| zwalletcli  | staging  |
| 0chain  | write_pools  |
| blobber  | remove_write_pools  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-07-20 13:16 UTC, sum-it08 requested changes

2022-07-20 13:16 UTC, ssardana08 commented on code/go/0chain.net/smartcontract/benchmark/main/config/benchmark.yaml
> -      min_lock_period: 2m
similar changes needs to be made on `docker.local/config/loadtest_benchmark.yaml`

2022-07-20 13:31 UTC, sum-it08 approved these changes
lgtm

2022-07-21 11:14 UTC, peterlimg approved these changes
lgtm

2022-07-26 17:06 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | remove/writepool  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | remove_write_pool  |
| zwalletcli  | staging  |
| 0chain  | write_pools  |
| blobber  | remove_write_pools  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | master  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-07-26 18:44 UTC, service-0chain commented
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | remove/writepool  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | remove_write_pool  |
| zwalletcli  | staging  |
| 0chain  | write_pools  |
| blobber  | remove_write_pools  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | master  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-07-26 20:27 UTC, merged