EventsDB: Foreign Keys to ReadMarker Table
0chain/0chain pull request #1493
Opened 2022-07-12 13:42 UTC by iamrz1

## Fixes
https://github.com/0chain/0chain/issues/897
## Need to be mentioned in CHANGELOG.md?

## Tests
Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/0chain/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

2022-07-13 14:50 UTC, peterlimg requested changes

2022-07-13 14:50 UTC, peterlimg commented on code/go/0chain.net/smartcontract/dbs/event/readmarker.go
> +	User2      User       `gorm:"foreignKey:OwnerID;references:UserID;constraint:OnUpdate:CASCADE,OnDelete:CASCADE"`
User2 is not a good name, perhaps change to Owner?

2022-07-13 14:52 UTC, iamrz1 commented on code/go/0chain.net/smartcontract/dbs/event/readmarker.go
> +	User2      User       `gorm:"foreignKey:OwnerID;references:UserID;constraint:OnUpdate:CASCADE,OnDelete:CASCADE"`
sure

2022-07-14 00:38 UTC, peterlimg approved these changes
lgtm

2022-07-14 03:23 UTC, service-0chain commented
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | true  |
| system-tests  | master  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | fk-read-markers  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | master  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-07-14 04:32 UTC, merged