0xhrsh/safe math ops
0chain/0chain pull request #1509
Opened 2022-07-17 17:08 UTC by 0xhrsh

## Fixes

## Changes

## Need to be mentioned in CHANGELOG.md?

## Tests
Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/0chain/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

## Associated PRs (Link as appropriate):
- blobber:
- gosdk:
- system_test:
- zboxcli:
- zwalletcli:
- Other: ...

2022-07-18 07:03 UTC, peterlimg requested changes

2022-07-18 07:03 UTC, peterlimg commented on code/go/0chain.net/smartcontract/stakepool/stakepool.go
> +			maths.SafeAddInt64(spUpdate.DelegateRewards[delegates[i].DelegateID], iShare)
Seems we don't need the `iShare, err := share.Int64()` conversion above, so we can call the currency.AddCoin here with share directly. Don't know why we convert it to int64 before.

2022-07-18 07:03 UTC, peterlimg commented on code/go/0chain.net/smartcontract/storagesc/allocation.go
> +		panic(err) // TODO: Better error handling
return error instead of panic

2022-07-18 07:03 UTC, peterlimg commented on code/go/0chain.net/core/maths/maths.go
> +// SafeAddFloat64 adds two integers and returns an error if there is overflows
Should be 'adds two float64 ...'

Also, math.MaxFloat64 plus small number would return math.MaxFloat64 instead of math.InF, see https://play.golang.com/p/8Rd7OTlCHq3

The math.MaxFloat64 would not overflow unless we add big number that is greater than 1e291.

2022-07-18 07:03 UTC, peterlimg commented on code/go/0chain.net/core/maths/maths.go
> +	return result, nil
This is the same as multiple two float64 values, so could use math.IsInf(1) and math.IsInf(-1) to check overflow

2022-07-18 07:03 UTC, peterlimg commented on code/go/0chain.net/smartcontract/storagesc/models.go
> +	// }
Return error

2022-07-18 07:03 UTC, peterlimg commented on code/go/0chain.net/smartcontract/storagesc/models.go
> +		panic(err)
return error

2022-07-18 07:03 UTC, peterlimg commented on code/go/0chain.net/smartcontract/storagesc/models.go
> +				panic(err)
return error

2022-07-18 07:03 UTC, peterlimg commented on code/go/0chain.net/smartcontract/storagesc/models.go
> +			panic(err) // TODO: handle error
return error

2022-07-18 07:05 UTC, peterlimg requested changes

2022-07-18 07:05 UTC, peterlimg commented on code/go/0chain.net/core/maths/maths.go
> +		return result, fmt.Errorf("Overflow multiplying %v and %v", a, b)
Let's not use capital error message

2022-07-18 19:09 UTC, 0xhrsh commented on code/go/0chain.net/core/maths/maths.go
> +// SafeAddFloat64 adds two integers and returns an error if there is overflows
So no need to check for overflow for add operations in float64?

2022-07-18 19:15 UTC, 0xhrsh commented on code/go/0chain.net/smartcontract/stakepool/stakepool.go
> +			maths.SafeAddInt64(spUpdate.DelegateRewards[delegates[i].DelegateID], iShare)
we'll need it because `spUpdate.DelegateRewards[delegates[i].DelegateID]` is int64

2022-07-19 00:38 UTC, peterlimg commented on code/go/0chain.net/smartcontract/stakepool/stakepool.go
> +			maths.SafeAddInt64(spUpdate.DelegateRewards[delegates[i].DelegateID], iShare)
We'd better change the `spUpdate.DelegateRewards` value type to uint64 or currency.Coin, @Sriep what do you think.

2022-07-19 01:05 UTC, peterlimg commented on code/go/0chain.net/core/maths/maths.go
> +// SafeAddFloat64 adds two integers and returns an error if there is overflows
Yes, we should be safe to do sum/multiple for float64 directly, as most of places are for calculating rewards, which is are all small numbers.

2022-07-19 01:36 UTC, peterlimg requested changes
We can use float64 directly for most of the places where they are for rewards

2022-07-19 01:36 UTC, peterlimg commented on code/go/0chain.net/smartcontract/minersc/models.go
> +	gn.RewardRate, err = maths.SafeMultFloat64(gn.RewardRate, (1.0 - gn.RewardDeclineRate))
We don't need to do the overflow check since the `1.0 - gn.RewardDeclineRate` should always be `>= 0 and <= 1`, which should be guaranteed when the `gn.RewardDeclineRate` is loaded and validated.

2022-07-19 01:36 UTC, peterlimg commented on code/go/0chain.net/smartcontract/minersc/models.go
> +	miner, err = currency.Float64ToCoin(fminer)
Same as above

2022-07-19 01:36 UTC, peterlimg commented on code/go/0chain.net/smartcontract/minersc/models.go
> +	dkgmn.T = int(math.Ceil(tF))
Unnecessary calling of safe float64 functions, the KPercent, TPercent are all value between 0 and 1, and the N is the total miners  number, they can not be overflow.

2022-07-19 01:36 UTC, peterlimg commented on code/go/0chain.net/smartcontract/storagesc/allocation.go
> +				return nil, fmt.Errorf("overflow while calculating expire time")
We don't need to worry about the time overflow in seconds, check https://stackoverflow.com/questions/25065055/what-is-the-maximum-time-time-in-go

2022-07-19 01:36 UTC, peterlimg commented on code/go/0chain.net/smartcontract/storagesc/challenge.go
> +		alloc.MovedBack, err = currency.AddCoin(alloc.MovedBack, back)
We should avoid return value to `alloc.MoveBack` directly, as if the `AddCoin()` failed, the `alloc.MovedBack` will be set to 0, which is not what we want.

2022-07-19 01:36 UTC, peterlimg commented on code/go/0chain.net/smartcontract/storagesc/challenge.go
> +		blobAlloc.Returned, err = currency.AddCoin(blobAlloc.Returned, back)
As above

2022-07-19 01:36 UTC, peterlimg commented on code/go/0chain.net/smartcontract/storagesc/challenge.go
> +	blobAlloc.ChallengeReward, err = currency.AddCoin(blobAlloc.ChallengeReward, blobberReward)
As above

2022-07-19 01:36 UTC, peterlimg commented on code/go/0chain.net/smartcontract/storagesc/challenge.go
> +	alloc.MovedToValidators, err = currency.AddCoin(alloc.MovedToValidators, validatorsReward)
As above

2022-07-19 01:36 UTC, peterlimg commented on code/go/0chain.net/smartcontract/storagesc/challenge.go
> +	alloc.MovedToValidators, err = currency.AddCoin(alloc.MovedToValidators, validatorsReward)
As above

2022-07-19 01:36 UTC, peterlimg commented on code/go/0chain.net/smartcontract/storagesc/challenge.go
> +	alloc.MovedBack, err = currency.AddCoin(alloc.MovedBack, move)
As above

2022-07-19 01:36 UTC, peterlimg commented on code/go/0chain.net/smartcontract/storagesc/challenge.go
> +	blobAlloc.Returned, err = currency.AddCoin(blobAlloc.Returned, move)
As above

2022-07-19 01:36 UTC, peterlimg commented on code/go/0chain.net/smartcontract/storagesc/challenge.go
> +		blobAlloc.Penalty, err = currency.AddCoin(blobAlloc.Penalty, move) // penalty statistic
As above

2022-07-19 01:36 UTC, peterlimg commented on code/go/0chain.net/smartcontract/storagesc/collect_reward.go
> +	conf.Minted, err = currency.AddCoin(conf.Minted, reward)
As above

2022-07-19 01:36 UTC, peterlimg commented on code/go/0chain.net/smartcontract/storagesc/stakepool.go
> +		ap.Balance, err = currency.AddCoin(ap.Balance, dpSlash)
As above

2022-07-22 01:34 UTC, peterlimg requested changes

2022-07-22 01:34 UTC, peterlimg commented on code/go/0chain.net/chaincore/chain/protocol_block.go
> +			verifiersStake, err = maths.SafeAddInt(verifiersStake, c.getMiningStake(ticket.VerifierID))
The `int` size is platform dependent, we'd better avoid using it for stake value, so let's change the `miningStake` type to uint64.

2022-07-22 01:34 UTC, peterlimg commented on code/go/0chain.net/miner/protocol_block.go
> +		newCost, err := maths.SafeAddInt(cost, c)
The `cost` is small number, not tokens, it represents the general CPU, RAM, etc resource cost for executing a smart contract. So we can ignore the overflow checking for them.

2022-07-22 01:34 UTC, peterlimg commented on code/go/0chain.net/miner/protocol_block.go
> +			tii.cost = newCost
As above

2022-07-22 01:34 UTC, peterlimg commented on code/go/0chain.net/miner/protocol_block.go
> +			iterInfo.cost = newCost
As above

2022-07-22 01:34 UTC, peterlimg commented on code/go/0chain.net/miner/protocol_block.go
> +		blockSize = newBlockSize
We don't need to check  overflow for block size

2022-07-22 01:34 UTC, peterlimg commented on code/go/0chain.net/smartcontract/minersc/fees.go
> +				panic(err) // TODO: handle this
Remember to handle the error

2022-07-22 01:34 UTC, peterlimg commented on code/go/0chain.net/smartcontract/stakepool/stakepool.go
> +			panic(err) // TODO: handle error
Return error

2022-07-22 01:34 UTC, peterlimg commented on code/go/0chain.net/smartcontract/storagesc/allocation_pool.go
> +			panic(err) // TODO: handle error
Return error

2022-07-22 01:34 UTC, peterlimg commented on code/go/0chain.net/smartcontract/storagesc/stakepool.go
> +			panic(err) // TODO: handle error
Return error

2022-07-22 01:34 UTC, peterlimg commented on code/go/0chain.net/smartcontract/vestingsc/vesting.go
> +			panic(err) // TODO: handle error
Return error

2022-07-22 01:34 UTC, peterlimg commented on code/go/0chain.net/smartcontract/vestingsc/vesting.go
> +			panic(err) // TODO: handle error
Return error

2022-07-22 15:27 UTC, 0xhrsh commented on code/go/0chain.net/smartcontract/stakepool/stakepool.go
> +			maths.SafeAddInt64(spUpdate.DelegateRewards[delegates[i].DelegateID], iShare)
Should I go ahead with this?

2022-07-22 15:28 UTC, 0xhrsh commented on code/go/0chain.net/chaincore/chain/protocol_block.go
> +			verifiersStake, err = maths.SafeAddInt(verifiersStake, c.getMiningStake(ticket.VerifierID))
I'll do this in a separate PR, that works?

2022-07-23 10:31 UTC, 0xhrsh commented on code/go/0chain.net/smartcontract/stakepool/stakepool.go
> +			maths.SafeAddInt64(spUpdate.DelegateRewards[delegates[i].DelegateID], iShare)
I can combine this with `miningStake` and make a separate PR for both?

2022-07-23 13:25 UTC, peterlimg commented on code/go/0chain.net/chaincore/chain/protocol_block.go
> +			verifiersStake, err = maths.SafeAddInt(verifiersStake, c.getMiningStake(ticket.VerifierID))
Sure, let's do it in a separate PR

2022-07-23 13:41 UTC, peterlimg approved these changes
lgtm, please fix the conflicts

2022-07-23 13:41 UTC, peterlimg commented on code/go/0chain.net/smartcontract/stakepool/stakepool.go
> +			maths.SafeAddInt64(spUpdate.DelegateRewards[delegates[i].DelegateID], iShare)
Yes, please do them in a separate PR

2022-07-31 16:28 UTC, merged