Fix cost overflow
0chain/0chain pull request #1523
Opened 2022-07-23 06:29 UTC by peterlimg

## Fixes

Calculate the build-in txn costs ahead and occupies the txn slot in block ahead before collecting txns from pool

## Changes

## Need to be mentioned in CHANGELOG.md?

## Tests
Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/0chain/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

## Associated PRs (Link as appropriate):
No

2022-07-23 08:03 UTC, sum-it08 approved these changes
lgtm

2022-07-23 09:46 UTC, dabasov requested changes
sometimes you don’t know which of this 4 transactions should be included in the block and can figure out it only after all transactions are collected to the block, it was intentionally done this way.

2022-07-23 12:17 UTC, peterlimg commented
They should be included whenever possible, that's why we calculate the costs before collecting the txns.

2022-08-08 04:02 UTC, service-0chain commented
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | TRUE  |
| system-tests  | master  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | fix/cost-overflow  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | master  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-09-04 12:22 UTC, dabasov commented
it should be reasonable to change costs of this 4 transactions in the config, if we want to merge this PR

2022-09-29 19:52 UTC, dabasov approved these changes
lgtm

2022-09-29 19:52 UTC, merged

2022-09-29 20:44 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | master  |
| 0proxy  | staging  |
| 0search  | staging  |