remove invalid transactions on block finalization
0chain/0chain pull request #1562
Opened 2022-08-03 13:45 UTC by dabasov

2022-08-05 05:15 UTC, peterlimg requested changes

2022-08-05 05:15 UTC, peterlimg commented on code/go/0chain.net/chaincore/transaction/worker.go
> +					if current.Nonce <= fromList.Nonce {
The txn.GetKey() returns the transaction hash, so the nonce would always be the same as they are the same transaction.

2022-08-08 04:00 UTC, peterlimg submitted a review, later dismissed

2022-08-08 04:00 UTC, peterlimg commented on code/go/0chain.net/chaincore/transaction/worker.go
> +			list := mappedTxns[txn.GetKey()]
Seems the `txn` is an empty transaction, so I think the list is empty too.

2022-08-08 04:00 UTC, peterlimg commented on code/go/0chain.net/chaincore/transaction/worker.go
> +		mappedTxns[blockTx.GetKey()] = append(mappedTxns[blockTx.GetKey()], blockTx)
What's the mappedTxns key, seems it's txn hash, but perhaps should be client id.

2022-09-30 14:34 UTC, boddumanohar approved these changes
LGTM

2022-10-01 10:34 UTC, merged