get blobbers by rank
0chain/0chain pull request #1598
Opened 2022-08-15 15:25 UTC by Sriep

## Fixes
New endpoint to return a list of blobber ids ordered by rank.
## Changes

## Need to be mentioned in CHANGELOG.md?

## Tests
Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/0chain/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

## Associated PRs (Link as appropriate):
- blobber:
- gosdk:
- system_test:
- zboxcli:
- zwalletcli:
- Other: ...

2022-08-16 10:36 UTC, dabasov approved these changes
lgtm, should be merged after snapshot PR

2022-08-17 00:41 UTC, peterlimg requested changes

2022-08-17 00:41 UTC, peterlimg commented on code/go/0chain.net/smartcontract/storagesc/handler.go
> +		common.Respond(w, r, nil, common.NewErrInternal("no db connection"))
return

2022-08-23 06:58 UTC, peterlimg approved these changes
lgtm

2022-08-23 06:58 UTC, merged