adds config to chain during genesis
0chain/0chain pull request #1611
Opened 2022-08-22 21:03 UTC by 0xhrsh

## Fixes
fixes #687 
## Changes

## Need to be mentioned in CHANGELOG.md?

## Tests
Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/0chain/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

## Associated PRs (Link as appropriate):
- blobber:
- gosdk:
- system_test:
- zboxcli:
- zwalletcli:
- Other: ...

2022-08-25 11:29 UTC, peterlimg requested changes

2022-08-25 11:29 UTC, peterlimg commented on code/go/0chain.net/chaincore/chain/entity.go
> +	_, err := minersc.GetGlobalNode(state)
`minersc.GetGlobalNode` it self would not store the config to the state, though it also should not save state to it as `get` action should not change anything. What we need to do in this PR is something like:

```go
if err := minersc.InitConfig(state); err != nil {
    panic(err)
}
if err := storagesc.InitConfig(state); err != nil {
    panic(err)
}

...
and other smart contract packages.
```

2022-09-21 11:25 UTC, peterlimg requested changes

2022-09-21 11:25 UTC, peterlimg commented on code/go/0chain.net/smartcontract/minersc/sc.go
> +func ReadConfig(
Rename to InitConfig() and save the config to MPT if it's not in MPT yet.

2022-10-02 05:22 UTC, peterlimg requested changes
@0xhrsh the current changes looks good to me for initializing config for minersc. The global config in minersc would only load minersc related configs from yaml and store them to MPT. Please also do this for other smart contracts as well.

2022-10-14 05:10 UTC, peterlimg requested changes

2022-10-14 05:10 UTC, peterlimg commented on code/go/0chain.net/smartcontract/storagesc/config.go
> +	_, err = balances.InsertTrieNode(STORAGESC_CONFIG_KEY, conf)
Insert only when MPT does not have the config(retunr util.ErrValueNotPresent error), otherwise the config will be reset to default after restarting

2022-10-14 05:10 UTC, peterlimg commented on code/go/0chain.net/smartcontract/storagesc/config.go
> +		return InitConfig(balances)
Once we init config on genesis, this `getConfig()` should be `read` only.

2022-10-14 05:10 UTC, peterlimg commented on code/go/0chain.net/smartcontract/vestingsc/config.go
> +	_, err = balances.InsertTrieNode(VESTINGSC_CONFIG_KEY, conf)
Same as storagesc, insert on ErrValueNotPresent

2022-10-14 05:10 UTC, peterlimg commented on code/go/0chain.net/smartcontract/vestingsc/config.go
> +		return InitConfig(balances)
Same as storagesc, the `getConfig` should be read only

2022-10-14 05:10 UTC, peterlimg commented on code/go/0chain.net/smartcontract/zcnsc/nodes_reader.go
> +		node.ZCNSConfig = getConfig()
Do not insert if err is nil, which means the config exist, the insert will overwritten the config.

2022-10-18 04:49 UTC, peterlimg commented
@0xhrsh the system tests is failing because the faucet `config.ID` is initialized. I'll merge my fixes.

2022-10-18 06:20 UTC, peterlimg commented
The [scConfigKey](https://github.com/0chain/0chain/blob/8fe25622400d719d6bffd9deb907edf5238cea37/code/go/0chain.net/smartcontract/vestingsc/config.go#L66) is different from the `VESTINGSC_CONFIG_KEY`, which caused the config read API handler get different config value. @0xhrsh please fix them, remove the `scConfigKey` to avoid it being misused. Please also check other packages for this issue as well.

2022-10-21 11:46 UTC, service-0chain commented
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | TRUE  |
| system-tests  | master  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | 0xhrsh/config-setup-during-genesis  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | master  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-10-21 12:03 UTC, peterlimg approved these changes
lgtm

2022-10-21 12:03 UTC, merged