Add node size limit for MPT note
0chain/0chain pull request #1623
Opened 2022-08-28 15:50 UTC by uneet7

## Fixes
[#1085](https://github.com/0chain/0chain/issues/1085)
## Changes

## Need to be mentioned in CHANGELOG.md?

## Tests
Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/0chain/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

## Associated PRs (Link as appropriate):
- blobber:
- gosdk:
- system_test:
- zboxcli:
- zwalletcli:
- Other: ...

2022-08-29 05:33 UTC, peterlimg requested changes

2022-08-29 05:33 UTC, peterlimg commented on code/go/0chain.net/core/util/markle_patricia_trie_interface.go
> +	MPTMaxAllowableNodeSize = 1000000 // 1 MB
We'd better put this const in another place that separate it from the PruneState, so perhaps put it in the head of the file above the `ErrIteratingChildNodes`.

2022-08-31 10:33 UTC, peterlimg requested changes

2022-08-31 10:33 UTC, peterlimg commented on code/go/0chain.net/core/util/markle_patricia_trie_interface.go
> +	MPTMaxAllowableNodeSize = 1000000 // 1 MB
Let's use 1024*1024 for 1MB

2022-09-03 14:32 UTC, dabasov approved these changes
lgtm

2022-09-11 11:16 UTC, uneet7 commented
Closing the PR, because the piece is moved into the `common` repo

2022-09-11 11:16 UTC, closed without merging