Register authorizers check
0chain/0chain pull request #1661
Opened 2022-09-13 06:35 UTC by uneet7

## Fixes
#1602 

## Changes
## Need to be mentioned in CHANGELOG.md?

## Tests
Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/0chain/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

## Associated PRs (Link as appropriate):
- blobber:
- gosdk:
- system_test:
- zboxcli:
- zwalletcli:
- Other: ...

2022-09-13 12:15 UTC, dabasov requested changes

2022-09-13 12:15 UTC, dabasov commented on code/go/0chain.net/smartcontract/zcnsc/authorizer.go
> +		return authorizerID != params.StakePoolSettings.DelegateWallet
delete this check as we already have one

2022-09-15 19:24 UTC, dabasov approved these changes
lgtm

2022-09-19 06:55 UTC, peterlimg requested changes

2022-09-19 06:55 UTC, peterlimg commented on code/go/0chain.net/smartcontract/zcnsc/authorizer.go
> +	// transaction type can only be executed by sc owner
The comment should be 'only sc owner can add new authorizer'. In another way to say is that this transaction will be executed only when it is created and signed by the sc owner. Transactions are executed by miners, not the sc owner.

2022-09-26 02:14 UTC, peterlimg approved these changes
lgtm, please fix the conflicts

2022-09-28 14:39 UTC, service-0chain commented
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | 1602-register-authorizers-check  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | master  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-09-29 12:47 UTC, merged

2022-09-29 13:30 UTC, peterlimg commented on code/go/0chain.net/smartcontract/zcnsc/authorizer.go
> +	clientId = encryption.Hash(publicKeyBytes)
We don't need to get clientID from publicKey as the txn.ClientID has already be verified when the txn is collected.

2022-09-29 14:18 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | master  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-09-29 15:29 UTC, service-0chain commented
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | master  |
| 0proxy  | staging  |
| 0search  | staging  |