[WIP] Add validations for put transaction to check clock sync
0chain/0chain pull request #1779
Opened 2022-10-30 13:22 UTC by uneet7

## Fixes
#1673 

## Changes

## Need to be mentioned in CHANGELOG.md?

## Tests
Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/0chain/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

## Associated PRs (Link as appropriate):
- blobber:
- gosdk:
- system_test:
- zboxcli:
- zwalletcli:
- Other: ...

2022-10-30 15:03 UTC, dabasov requested changes

2022-10-30 15:03 UTC, dabasov commented on code/go/0chain.net/chaincore/chain/handler.go
> +	cb, err := sc.GetBlock(ctx, txn.Hash)
it will return nothing, since this transaction is not in the block

2022-10-31 23:19 UTC, peterlimg approved these changes

2022-10-31 23:19 UTC, peterlimg commented
@uneet7 is there anything else need to be added, or I will merge it.

2022-11-01 15:28 UTC, dabasov approved these changes
lgtm

2022-11-01 16:31 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | 1673-add-suggestion-for-user-if-his-local-time-is-not-synced-with-the-time-of-blockchain  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | master  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-11-02 02:01 UTC, uneet77 commented
Not needed. We can merge it

2022-11-02 03:55 UTC, peterlimg commented
The system tests errors are not related to this PR, I'll mark this as passed and merge it.

2022-11-02 03:56 UTC, service-0chain commented
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | TRUE  |
| system-tests  | master  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | 1673-add-suggestion-for-user-if-his-local-time-is-not-synced-with-the-time-of-blockchain  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | master  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-11-02 04:07 UTC, merged