Fix rewards
0chain/0chain pull request #1792
Opened 2022-11-07 09:49 UTC by Sriep

## Fixes
Increment provider rewards table when rewards are given.
## Changes

## Need to be mentioned in CHANGELOG.md?

## Tests
Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/0chain/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

## Associated PRs (Link as appropriate):
- blobber:
- gosdk:
- system_test:
- zboxcli:
- zwalletcli:
- Other: ...

2022-11-08 13:14 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | fix_rewards  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | master  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-11-10 20:14 UTC, service-0chain commented
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | fix_rewards  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | master  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-11-11 18:38 UTC, service-0chain commented
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | rewards_zeroed  |
| gosdk  | update_blobber_object  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | fix_rewards  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-11-14 05:01 UTC, peterlimg requested changes

2022-11-14 05:01 UTC, peterlimg commented on code/go/0chain.net/smartcontract/dbs/event/stakepool.go
> +		if err := edb.incrementReward(spus[i].ProviderId, spus[i].Reward); err != nil {
Why do we replace the batch update of provider rewards with this separated sql exec

2022-11-14 05:01 UTC, peterlimg commented on code/go/0chain.net/smartcontract/dbs/event/stakepool.go
> +*/
Any reason for why we don't use this

2022-11-14 05:01 UTC, peterlimg commented on code/go/0chain.net/smartcontract/minersc/collect_reward.go
> +				err = fmt.Errorf("unsupported provider type %s", crr.ProviderType.String())
The `%s` will call the `String()` for us, so as long the ProviderType implemented the `Stringer` interface, we can just pass it

2022-11-14 05:01 UTC, peterlimg commented on code/go/0chain.net/smartcontract/minersc/collect_reward.go
> +	)
We should always check error first to avoid 'node not found' error getting ignored and then cause 'state hash mismatch' error. 

Imagine the miner got 'node not found' error here, all the state changes above would be invalid, but if we continue and somehow get 'value not present' or some other chargerable error below in line 62, this txn will be included to the block, and due to the invalid state we have got above, this block will get different from other miners. Although this will be finally captured on top txn executor, but we'd better avoid this kind of error at the beginning.

2022-11-14 05:01 UTC, peterlimg commented on code/go/0chain.net/smartcontract/minersc/collect_reward.go
> +	return "", err
Perhaps we should provide option to collect rewards from all of the user's pools

2022-11-14 05:01 UTC, peterlimg commented on code/go/0chain.net/smartcontract/minersc/delegate_pools.go
>  	if numDelegates >= gn.MaxDelegates {
Do the existing pool checking for this max delegates checking perhaps?

2022-11-14 05:01 UTC, peterlimg commented on code/go/0chain.net/smartcontract/stakepool/lock.go
> +	var err error
Move the err declare to the nearest place where it will be used. So I suppose it is around line 82.

2022-11-14 05:01 UTC, peterlimg commented on code/go/0chain.net/smartcontract/stakepool/userstakepoolgo.go
> -type UserStakePools struct {
How can we get all pools of a user from miners without event db. So if we want to implement collect all rewards, users will need to get all pools by calling API from sharder, then send txn to collect rewards?

2022-11-14 05:01 UTC, peterlimg commented on code/go/0chain.net/smartcontract/storagesc/config.go
> +	return nil
Could be`return err`, unnecessary error check

2022-11-14 11:19 UTC, Sriep commented on code/go/0chain.net/smartcontract/minersc/collect_reward.go
> +	return "", err
When we collect rewards from a user pool we have to update a Reward field in the MPT. The maximum number of user pools is of order the number of providers in the 0chain, far too many MPT updates to handle.

2022-11-14 11:26 UTC, Sriep commented on code/go/0chain.net/smartcontract/stakepool/userstakepoolgo.go
> -type UserStakePools struct {
We do not want to implement collect all rewards, it would potentially involve too many MPT updates. Third-party software will have to handle this.

2022-11-14 17:45 UTC, dabasov commented
please, merge after snapshot

2022-11-14 18:04 UTC, Sriep commented
This Pr is a blocker for my work on system tests. I cannot progress with rewards system tests unless 0chain rewards are fixed.

2022-11-23 11:07 UTC, Sriep commented
Replaced by https://github.com/0chain/0chain/pull/1828 and https://github.com/0chain/0chain/pull/1829 and https://github.com/0chain/0chain/pull/1832 and https://github.com/0chain/0chain/pull/1833.

2022-11-23 13:22 UTC, closed without merging