1769 minerssharders nodes could be added without limitation
0chain/0chain pull request #1802
Opened 2022-11-13 07:36 UTC by devyetii

## Fixes

## Changes
- Add NodeListLength type as a new type of nodes that can be saved in the MPT
- Add 2 new node keys with their accessors/mutators (MinerListLength/SharderListLength)
- Use these two nodes to track the growth/shrinkage of the list
- Put conditions on the growth of the list

## Need to be mentioned in CHANGELOG.md?
- IDK
## Tests
Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/0chain/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

## Associated PRs (Link as appropriate):
- blobber:
- gosdk:
- system_test:
- zboxcli:
- zwalletcli:
- Other: ...

2022-11-14 05:42 UTC, peterlimg commented
@devyetii this would not be able to prevent the attack actually, suppose we set the max miners number as 100, attackers could occupy all or most of the positions by adding fake nodes to the list, then honest miners would just failed to join the network due to the max limit reached.

2022-11-14 05:54 UTC, peterlimg commented
One possible way to prevent this kind of attack before enabling VC is checking the magic block to see if the nodes are in the magic block nodes list. This fix would not work if we enable the VC later, but could be a shot term fix. 

After enabling the VC, perhaps we can add a minimal staking requirement when adding a new miner, so if it is the first time the miner come to the network, the add_miner txn the miner send must provide minimal staking tokens. In this way, we can prevent spam nodes in certain extent, and the VC process will then ensure that those nodes do not obey the rules get removed from the magic block. @guruhubb what do you think.

2022-11-14 12:09 UTC, dabasov commented
we discussed with @devyetii similar approach with staking just when node is added. I suggest to implement it together with view-change, as it is tightly coupled with this process, for now we can hard cap miners and check if it is the same set as in magic block, while we are not changing magic block it should work

2022-11-22 16:05 UTC, service-0chain commented
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | increase_settingUpdateSleepTime  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | 1769-minerssharders-nodes-could-be-added-without-limitation  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | master  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-11-22 17:29 UTC, devyetii commented
@peterlimg After pushing a small change - just changing the waiting time between two lines ([link](https://github.dev/0chain/system_test/blob/360139c28b67d7d7397b5afef199a743d97c9e6c/tests/cli_tests/zwalletcli_storage_update_config_test.go#L90-L91), I ran the system tests branch I pushed to against this branch and it passed successfully : https://github.com/0chain/0chain/actions/runs/3524409881/jobs/5909774247

2022-12-19 14:38 UTC, dabasov requested changes

2022-12-19 14:38 UTC, dabasov commented on code/go/0chain.net/smartcontract/minersc/miner.go
> +	lockAllMiners.Lock()
why do we need this lock?

2022-12-19 14:39 UTC, dabasov requested changes

2022-12-19 14:39 UTC, dabasov commented on code/go/0chain.net/smartcontract/minersc/models.go
> +func IncrementMinerListLength(state cstate.QueryStateContextI) (*NodeListLength, error) {
where is this func used?

2022-12-19 14:39 UTC, dabasov commented on code/go/0chain.net/smartcontract/minersc/models.go
> +func DecrementMinerListLength(state cstate.QueryStateContextI) (*NodeListLength, error) {
where is it used?

2022-12-20 08:18 UTC, service-0chain commented
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | 1769-minerssharders-nodes-could-be-added-without-limitation  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | master  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-12-20 10:06 UTC, dabasov approved these changes
lgtm

2022-12-20 10:06 UTC, merged

2022-12-20 11:29 UTC, peterlimg commented on code/go/0chain.net/smartcontract/minersc/miner.go
> +	if magicBlockMiners.HasNode(newMiner.ID) == false {
Please do `if !magicBlockMiners.HasNode(newMiner.ID)`