increase allowed value of storagesc max_stake
0chain/0chain pull request #1937
Opened 2022-12-26 13:55 UTC by boddumanohar

## Fixes

## Changes

## Need to be mentioned in CHANGELOG.md?

## Tests
Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/0chain/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

## Associated PRs (Link as appropriate):
- blobber:
- gosdk:
- system_test:
- zboxcli:
- zwalletcli:
- Other: ...

2022-12-26 17:59 UTC, dabasov requested changes

2022-12-26 17:59 UTC, dabasov commented on code/go/0chain.net/smartcontract/storagesc/handler.go
> +// # This endpoint returns the summation of all the Size fields in all the WriteMarkers sent to 0chain by blobbers
we don't need `#`

2022-12-26 19:18 UTC, dabasov approved these changes
lgtm

2022-12-27 19:47 UTC, service-0chain commented
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | TRUE  |
| system-tests  | master  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | update-storagesc-max-stake  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | master  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-12-27 19:49 UTC, merged