Fix/conductor blobber
0chain/0chain pull request #1953
Opened 2022-12-30 05:52 UTC by Manali-Jain-squareops

## Fixes

## Changes

## Need to be mentioned in CHANGELOG.md?

## Tests
Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/0chain/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

## Associated PRs (Link as appropriate):
- blobber:
- gosdk:
- system_test:
- zboxcli:
- zwalletcli:
- Other: ...

2022-12-30 05:53 UTC, Manali-Jain-squareops commented
@fabioDMFerreira 
for issue https://github.com/0chain/0chain/actions/runs/3805043968/jobs/6472690027

fixed after this push https://github.com/0chain/0chain/actions/runs/3805082066/jobs/6472751195

2022-12-30 06:20 UTC, guruhubb approved these changes

2023-01-01 19:47 UTC, dabasov requested changes

2023-01-01 19:47 UTC, dabasov commented on docker.local/config/0chain.yaml
> -max_stake: 20000.0 # tokens
why is this required?

2023-01-02 04:26 UTC, Manali-Jain-squareops commented
this fixed integration test 
@boddumanohar know in detail

2023-01-09 20:11 UTC, closed without merging