1963 logs clean up
0chain/0chain pull request #2045
Opened 2023-01-24 23:11 UTC by devyetii

## Fixes
I'm following these rules - as much as possible, may have some exceptions. 
1. Use `zap.<Type>` instead of `zap.Any` whenever the type is supported by zap.
2. Remove any unneeded/debugging `zap.Any` from the logs.
3. Log IDs instead of the full objects esp. for `Node`s, `Block`s and `Transaction`s
4. Leave `zap.Any` if it's
  1. Used with a simple custom type e.g. `currency.Coin` 
  2. Logs a **single, not so big** object from a complex type
  3. Logs once or a limited number of times during the nodes lifetime.
5. Use `Logger.Error` whenever an error is logged.
6. Use `zap.Error(err)` instead of `zap.Any("error", err)`
## Changes

## Need to be mentioned in CHANGELOG.md?

## Tests
Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/0chain/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

## Associated PRs (Link as appropriate):
- blobber:
- gosdk:
- system_test:
- zboxcli:
- zwalletcli:
- Other: ...

2023-01-24 23:12 UTC, devyetii commented
@peterlimg @dabasov Kindly review, esp. where I log`txn.Hash` instead of `txn`.

2023-01-25 09:37 UTC, peterlimg approved these changes
LGTM

2023-01-25 09:42 UTC, peterlimg requested changes
Please fix the unit tests build errors.

2023-01-25 09:42 UTC, peterlimg commented on code/go/0chain.net/chaincore/chain/state.go
> +				zap.String("txn", txn.Hash))
Please log the txn as it can be helpful when we need to debug, same as the other places for txn below.

2023-01-25 14:16 UTC, devyetii commented
@peterlimg Now all successful. Kindly check and merge.

2023-01-27 01:06 UTC, peterlimg approved these changes
LGTM

2023-01-27 01:06 UTC, merged