WIP: User aggregates and snapshots table
0chain/0chain pull request #2050
Opened 2023-01-26 08:01 UTC by manasnisar

## Fixes

## Changes

## Need to be mentioned in CHANGELOG.md?

## Tests
Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/0chain/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

## Associated PRs (Link as appropriate):
- blobber:
- gosdk:
- system_test:
- zboxcli:
- zwalletcli:
- Other: ...

2023-01-30 15:43 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | anas/feature/user-aggr  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | master  |
| 0proxy  | staging  |
| 0search  | staging  |

2023-02-01 17:25 UTC, dabasov requested changes
please remove

2023-02-01 17:25 UTC, dabasov commented on code/go/0chain.net/smartcontract/stakepool/lock.go
> +	balances.EmitEvent(event.TypeStats, event.TagLockStakePool, newPoolId, event.User{
is it safe to change lock to User?

2023-02-01 17:25 UTC, dabasov commented on code/go/0chain.net/smartcontract/dbs/event/process.go
> +			mergeDecreaseUserTotalStakeEvents(),
why do we need 2 different mergers to increase and decrease stake?

2023-02-01 17:25 UTC, dabasov commented on code/go/0chain.net/smartcontract/dbs/event/user.go
> +	operation := "+"
we do not this hack, simply convert `u.WritePoolTotal` to int64 and use negative if you need to decrease

2023-02-01 17:25 UTC, dabasov commented on code/go/0chain.net/smartcontract/dbs/event/user_aggregate.go
> +	PayedFees       currency.Coin `json:"payed_fees"`
we use raw type for this fields, since it's easy to work with them

2023-02-01 17:25 UTC, dabasov commented on code/go/0chain.net/smartcontract/dbs/event/user.go
> +		AddUpdate("write_pool_total", writepools, "users.write_pool_total "+operation+" t.write_pool_total").Exec(edb).Error
It's not correct, we should overwrite current value with new one, since `t.write_pool_total` is a result, not a delta

2023-02-04 19:03 UTC, dabasov requested changes

2023-02-04 19:03 UTC, dabasov commented on code/go/0chain.net/smartcontract/dbs/event/user.go
> +		AddUpdate("read_pool_total", readpools, "t.read_pool_total").Exec(edb).Error
you will update this field with negative value, I thought we discussed that here you should have
```go
    AddUpdate("read_pool_total", readpools, "users.read_pool_total + t.read_pool_total")
```

btw to update value with another one, you can use simply
```go
AddUpdate("read_pool_total", readpools)
```

2023-02-04 19:03 UTC, dabasov commented on code/go/0chain.net/smartcontract/dbs/event/user.go
> +		AddUpdate("write_pool_total", writepools, "t.write_pool_total").Exec(edb).Error
the same here

2023-02-04 19:03 UTC, dabasov commented on code/go/0chain.net/smartcontract/dbs/event/user.go
> +		AddUpdate("total_stake", stakes, "t.total_stake").Exec(edb).Error
the same here

2023-02-04 19:03 UTC, dabasov commented on code/go/0chain.net/smartcontract/dbs/event/user.go
> +		AddUpdate("collected_reward", collectedRewards, "t.collected_reward").Exec(edb).Error
the same here

2023-02-07 21:31 UTC, dabasov approved these changes
lgtm

2023-02-07 21:31 UTC, merged

2023-02-08 00:17 UTC, peterlimg commented on code/go/0chain.net/smartcontract/dbs/event/user.go
> +	return newEventsMerger[DelegatePoolLock](TagLockStakePool, withUniqueEventOverwrite())
This `withUniqueEventOverwrite()` will overwrite the previous one if there are more than one event from the same client, but the `TagLockStakePool` gives the `delta` value, we need to accumulate all of them. Please check https://github.com/0chain/0chain/blob/72a87c194322d79fafa7189cf99de7e210f2ec74/code/go/0chain.net/smartcontract/dbs/event/allocation.go#L249-L258 to see how to add up the values. And please also check other tags.