Fix/review exempt list
0chain/0chain pull request #2053
Opened 2023-01-26 14:35 UTC by devyetii

## Fixes
#1921 
## Changes

## Need to be mentioned in CHANGELOG.md?

## Tests
Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/0chain/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

## Associated PRs (Link as appropriate):
- blobber:
- gosdk:
- system_test:
- zboxcli:
- zwalletcli:
- Other: ...

2023-01-26 17:09 UTC, dabasov requested changes, later dismissed

2023-01-26 17:09 UTC, dabasov commented on code/go/0chain.net/smartcontract/storagesc/allocation.go
> +		emitUpdateBlobber(b, balances)
why do we need to this call?

2023-01-27 00:50 UTC, peterlimg commented
@dabasov I'm not sure if we should remove health check and `add_miner`, `add_sharder`, etc from the list as when I do txn fee PRs tests, those txns will fail to work due to the fee requirement.

2023-01-27 16:32 UTC, dabasov commented
> @dabasov I'm not sure if we should remove health check and `add_miner`, `add_sharder`, etc from the list as when I do txn fee PRs tests, those txns will fail to work due to the fee requirement.

@peterlimg we discussed it with @guruhubb. all providers will have balance and will be refreshed periodically. the problem with free health checks is that network can be easily DDOSed, we should not have any exempt transactions at all, after the mainnet we will make mint fees to be payed from the minted amount

2023-01-28 09:47 UTC, peterlimg approved these changes
LGTM

2023-01-28 09:59 UTC, merged