Fix panic in sharders
0chain/0chain pull request #2060
Opened 2023-01-29 21:53 UTC by Kishan-Dhakan

## Fixes
- Panic created by concurrent iteration and write in map

## Changes

## Need to be mentioned in CHANGELOG.md?

## Tests
Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/0chain/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

## Associated PRs (Link as appropriate):
- blobber:
- gosdk:
- system_test:
- zboxcli:
- zwalletcli:
- Other: ...

2023-01-30 02:27 UTC, peterlimg requested changes, later dismissed
@Kishan-Dhakan good catch, please make sure the `UniqueBlockExtensions` map is protected in all the places where it is used. And perhaps make it private and access it through method with lock protection.

2023-01-31 16:22 UTC, guruhubb approved these changes

2023-01-31 17:23 UTC, service-0chain commented
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | TRUE  |
| system-tests  | master  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | fix/map-panic  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | master  |
| 0proxy  | staging  |
| 0search  | staging  |

2023-01-31 17:24 UTC, merged

2023-02-01 02:45 UTC, peterlimg commented on code/go/0chain.net/chaincore/block/entity.go
> +	return b.uniqueBlockExtensions
We need to return the copy of the map, this returning would simply expose the map to public without locks protection.

2023-02-01 14:32 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | master  |
| 0proxy  | staging  |
| 0search  | staging  |