[WIP] Fix value not present
0chain/0chain pull request #2111
Opened 2023-02-14 13:25 UTC by din-mukhammed

## Fixes

## Changes

## Need to be mentioned in CHANGELOG.md?

## Tests
Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/0chain/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

## Associated PRs (Link as appropriate):
- blobber:
- gosdk:
- system_test:
- zboxcli:
- zwalletcli:
- Other: ...

2023-02-14 23:41 UTC, peterlimg requested changes

2023-02-14 23:41 UTC, peterlimg commented on code/go/0chain.net/chaincore/chain/entity.go
> +	err = minersc.InitGlobalSettings(stateCtx)
Let's do it in `minersc.InitConfig`

2023-02-15 11:15 UTC, peterlimg approved these changes
LGTM, please merge staging after #2115 to pass the checking errors

2023-02-16 09:55 UTC, dabasov approved these changes
lgtm

2023-02-17 05:25 UTC, merged