Anas/fix/repl query
0chain/0chain pull request #2126
Opened 2023-02-16 19:03 UTC by manasnisar

## Fixes

## Changes

## Need to be mentioned in CHANGELOG.md?

## Tests
Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/0chain/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

## Associated PRs (Link as appropriate):
- blobber:
- gosdk:
- system_test:
- zboxcli:
- zwalletcli:
- Other: ...

2023-02-18 12:29 UTC, dabasov requested changes

2023-02-18 12:29 UTC, dabasov commented on code/go/0chain.net/smartcontract/dbs/event/authorizer_aggregate.go
> -
let's refactor and remove this duplication for different providers

2023-02-18 12:29 UTC, dabasov commented on code/go/0chain.net/smartcontract/dbs/event/authorizer_aggregate.go
> -
extract common method where we can pass table name and structure to scan into

2023-02-19 15:37 UTC, dabasov approved these changes
lgtm

2023-02-20 04:19 UTC, peterlimg approved these changes
LGTM

2023-02-20 04:19 UTC, merged