Filter Validators
0chain/0chain pull request #2175
Opened 2023-02-27 14:09 UTC by Hitenjain14

## Changes
Filter validators according to LastHealthCheck . 

## Need to be mentioned in CHANGELOG.md?

## Tests
Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/0chain/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

## Associated PRs (Link as appropriate):
- blobber:
- gosdk:
- system_test:
- zboxcli:
- zwalletcli:
- Other: ...

2023-02-27 15:44 UTC, dabasov approved these changes
lgtm

2023-02-27 17:15 UTC, dabasov approved these changes
lgtm

2023-02-28 02:00 UTC, peterlimg requested changes

2023-02-28 02:00 UTC, peterlimg commented on code/go/0chain.net/smartcontract/storagesc/challenge.go
> +				continue
We need to check if the err is `node not found` error, and we need to return immediately if it is to avoid `mismatched state` error that will cause network stuck. So we can do

```go
if cstate.ErrInvalidState(err) {
    return err
}
```

2023-02-28 02:00 UTC, peterlimg commented on code/go/0chain.net/smartcontract/storagesc/challenge.go
> +			kick, err := filterValidator(validator)
Check if the returned `err` is necessary, I find there's no error returned in `filterHealthyValidators` actualy.

2023-02-28 09:05 UTC, Hitenjain14 commented on code/go/0chain.net/smartcontract/storagesc/challenge.go
> +			kick, err := filterValidator(validator)
No there is no error returned , I was following the convention used for `filterBlobbers` .

2023-02-28 11:09 UTC, peterlimg commented on code/go/0chain.net/smartcontract/storagesc/challenge.go
> +			kick, err := filterValidator(validator)
okay, but please check error and return if any. Doing this is to make sure we won't get mismatched state in the future when the filter function involves MPT operation and return error.

2023-03-01 00:16 UTC, peterlimg requested changes

2023-03-01 00:16 UTC, peterlimg commented on code/go/0chain.net/smartcontract/storagesc/challenge.go
> +				continue
We don't need to include the `mismatched state` msg to the error, it is the one of the result that we will have if we don't return err here, the error itself is not `mismatched state`.

2023-03-03 00:18 UTC, peterlimg approved these changes
LGTM

2023-03-15 14:47 UTC, Hitenjain14 commented
Should not be merged until we make sure validators are sending health check txns .

2023-03-15 21:32 UTC, Hitenjain14 commented
This is the error we are getting  - 
    `Bad transaction cost	{"error": "no cost given for validator_health_check", "txn_hash": "569161647bbb2ccbfe53affe3cab90d96eacf3d5576b96e62f46fd89c3383a14"}` , I have asked @m-s-a-c to add the value and update the helm chart .

2023-03-16 08:16 UTC, merged

2023-03-16 13:34 UTC, shahnawaz-creator commented
added