adding user aggregates on change
0chain/0chain pull request #2178
Opened 2023-02-28 09:44 UTC by manasnisar

## Fixes

## Changes

## Need to be mentioned in CHANGELOG.md?

## Tests
Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/0chain/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

## Associated PRs (Link as appropriate):
- blobber:
- gosdk:
- system_test:
- zboxcli:
- zwalletcli:
- Other: ...

2023-02-28 16:09 UTC, service-0chain commented
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | anas/fix/client-aggrs  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | master  |
| 0proxy  | staging  |
| 0search  | staging  |

2023-03-09 15:34 UTC, dabasov approved these changes
lgtm

2023-03-10 00:27 UTC, peterlimg commented on code/go/0chain.net/smartcontract/dbs/event/user_aggregate.go
> +	var mappedAggrs = make(map[string]*UserAggregate, len(ua))
Should be `len(ids)`

2023-03-10 00:33 UTC, peterlimg requested changes

2023-03-10 00:33 UTC, peterlimg commented on code/go/0chain.net/smartcontract/dbs/event/user_aggregate.go
> +		aggr.Round = e.round
`aggr` is value, not pointer, `aggr.Round = e.round` would not change it actually.

2023-03-13 06:41 UTC, peterlimg approved these changes
LGTM

2023-03-13 06:41 UTC, merged