Remove register wallet endpoint
0chain/0chain pull request #2186
Opened 2023-03-03 14:05 UTC by harshitbansal05

## Fixes

Issue #2132 

## Changes

## Need to be mentioned in CHANGELOG.md?

## Tests
Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/0chain/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

## Associated PRs (Link as appropriate):
- blobber:
- gosdk:
- system_test:
- zboxcli:
- zwalletcli:
- Other: ...

2023-03-03 15:05 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | remove-register_wallet-command  |
| zwalletcli  | remove-register_wallet-command  |
| 0chain  | remove-register_wallet-endpoint  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | master  |
| 0proxy  | staging  |
| 0search  | staging  |

2023-03-06 00:48 UTC, peterlimg requested changes, later dismissed
Let's not remove the client cache, we only need to remove the endpoint, the way how the clients are persisted and cached should not be changed. Client's public key decoding is cpu intensive process, we'll have performance issue without the cache.

2023-03-06 00:48 UTC, peterlimg commented on code/go/0chain.net/chaincore/block/entity.go
> -		c, err := client.GetClientFromCache(t.ClientID)
We'd better not remove the clients cache as `c.SetPublicKey` is a cpu intensive process, we need to avoid it as much as possible.

2023-03-10 07:01 UTC, service-0chain commented
Manual system tests [cancelled] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | ABILITY TO SKIP TESTS IS DISABLED. SKIP_TESTS OPTION IGNORED.  |
| system-tests  | master  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | remove-register_wallet-command  |
| zwalletcli  | remove-register_wallet-command  |
| 0chain  | remove-register_wallet-endpoint  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | master  |
| 0proxy  | staging  |
| 0search  | staging  |

2023-04-06 09:43 UTC, service-0chain commented
Manual system tests [cancelled] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | staging  |
| zboxcli  | staging  |
| zwalletcli  | 2133_read_pool  |
| 0chain  | remove-register_wallet-endpoint  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | master  |
| 0proxy  | staging  |
| 0search  | staging  |

2023-04-12 09:37 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | staging  |
| zboxcli  | staging  |
| zwalletcli  | 2133_read_pool  |
| 0chain  | remove-register_wallet-endpoint  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

2023-04-12 15:34 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | staging  |
| zboxcli  | fix/remove-register  |
| zwalletcli  | fix/remove-register  |
| 0chain  | remove-register_wallet-endpoint  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

2023-04-14 20:15 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | fix/remove-register  |
| zboxcli  | fix/remove-register  |
| zwalletcli  | fix/remove-register  |
| 0chain  | remove-register_wallet-endpoint  |
| blobber  | fix/remove-register  |
| authorizer  | fix/remove-register  |
| 0box  | fix/remove-register  |
| 0dns  | staging  |

2023-04-15 12:35 UTC, service-0chain commented
Manual system tests [cancelled] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | fix/remove-register  |
| zboxcli  | fix/remove-register  |
| zwalletcli  | fix/remove-register  |
| 0chain  | remove-register_wallet-endpoint  |
| blobber  | fix/remove-register  |
| authorizer  | fix/remove-register  |
| 0box  | fix/remove-register  |
| 0dns  | staging  |

2023-04-15 14:35 UTC, service-0chain commented
Manual system tests [cancelled] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | fix/remove-register  |
| gosdk  | fix/remove-register  |
| zboxcli  | fix/remove-register  |
| zwalletcli  | fix/remove-register  |
| 0chain  | remove-register_wallet-endpoint  |
| blobber  | fix/remove-register  |
| authorizer  | fix/remove-register  |
| 0box  | fix/remove-register  |
| 0dns  | staging  |

2023-04-21 21:20 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | fix/remove-register  |
| gosdk  | staging  |
| zboxcli  | fix/remove-register  |
| zwalletcli  | fix/remove-register  |
| 0chain  | remove-register_wallet-endpoint  |
| blobber  | fix/remove-register  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

2023-04-22 15:24 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | fix/remove-register  |
| gosdk  | fix/remove-register  |
| zboxcli  | fix/remove-register  |
| zwalletcli  | fix/remove-register  |
| 0chain  | remove-register_wallet-endpoint  |
| blobber  | fix/remove-register  |
| authorizer  | staging  |
| 0box  | fix/remove-register  |
| 0dns  | staging  |

2023-04-22 16:15 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | fix/remove-register  |
| gosdk  | fix/remove-register  |
| zboxcli  | fix/remove-register  |
| zwalletcli  | fix/remove-register  |
| 0chain  | remove-register_wallet-endpoint  |
| blobber  | fix/remove-register  |
| authorizer  | fix/remove-register  |
| 0box  | fix/remove-register  |
| 0dns  | staging  |

2023-04-27 16:13 UTC, service-0chain commented
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | TRUE  |
| system-tests  | master  |
| gosdk  | staging  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | remove-register_wallet-endpoint  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

2023-04-27 16:13 UTC, merged