blobber slash from delegate balance
0chain/0chain pull request #2187
Opened 2023-03-03 21:02 UTC by Hitenjain14

## Fixes
Blobber slash is now deducted from [DelegatePool.Balance](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/dbs/event/delegate_pool.go#L24) and added to [DelegatePool.TotalPenalty](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/dbs/event/delegate_pool.go#L27).
#2122 

## Changes
Added new tag for `TagStakePoolPenalty`

Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/0chain/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

## Associated PRs (Link as appropriate):
- blobber:
- gosdk:
- system_test:
- zboxcli:
- zwalletcli:
- Other: ...

2023-03-04 14:53 UTC, dabasov requested changes

2023-03-04 14:53 UTC, dabasov commented on code/go/0chain.net/smartcontract/storagesc/stakepool.go
> +	if err := edbSlash.Emit(event.TagStakePoolPenalty, balances); err != nil {
is stake pool reduced for this amount? I don't see the reduction. At first we should reduce the stakepool and all the delegate pools proportionally in the MPT, and only after it update the events_db. looks like with current implementation events_db will be changed, but MPT won't and balances will be different in different storages

2023-03-04 17:07 UTC, dabasov commented on code/go/0chain.net/smartcontract/storagesc/stakepool.go
> +	if err := edbSlash.Emit(event.TagStakePoolPenalty, balances); err != nil {
here is the code 
```go
		if balance, err := currency.MinusCoin(dp.Balance, dpSlash); err != nil {
			return 0, err
		} else {
			dp.Balance = balance
		}
```

2023-03-04 17:07 UTC, dabasov approved these changes
lgtm

2023-03-05 14:26 UTC, Kishan-Dhakan commented
@Hitenjain14 can we add system-tests for this?

2023-03-06 00:55 UTC, peterlimg approved these changes
LGTM

2023-03-09 18:50 UTC, merged