Changes for Blobber and Validator Reward Testing
0chain/0chain pull request #2197
Opened 2023-03-06 16:06 UTC by Jayashsatolia403

## Fixes

## Changes

## Need to be mentioned in CHANGELOG.md?

## Tests
Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/0chain/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

## Associated PRs (Link as appropriate):
- blobber:
- gosdk:
- system_test:
- zboxcli:
- zwalletcli:
- Other: ...

2023-03-06 21:01 UTC, dabasov requested changes

2023-03-06 21:01 UTC, dabasov commented on code/go/0chain.net/smartcontract/dbs/goose/migrations/001_events_db.sql
> +                                         challenge_id text
better create new migration

2023-03-06 21:01 UTC, dabasov commented on code/go/0chain.net/smartcontract/storagesc/challenge.go
> +type TransactionData struct {
we do have this `ChallengeResponse`
usually we parse transaction only once and it is already parsed  before, check where `challengePassed()` is called

2023-03-06 21:01 UTC, dabasov commented on code/go/0chain.net/smartcontract/stakepool/stakepool.go
> +	if len(optional) > 0 {
van you call it like this?

```go
		spUpdate = NewStakePoolReward(providerId, providerType, rewardType, optional...)

```

2023-03-06 21:01 UTC, dabasov commented on code/go/0chain.net/smartcontract/storagesc/handler.go
> +		rest.MakeEndpoint(storage+"/reward-providers", srh.rewardProviders),
move it under `/test/*`

2023-03-07 12:04 UTC, peterlimg requested changes

2023-03-07 12:04 UTC, peterlimg commented on code/go/0chain.net/smartcontract/dbs/event/reward_provider.go
> +	edb.Get().Where("challenge_id = ? AND reward_type IN (6, 8, 9)", challengeID).Find(&rps)
Do not use magic number, the `6, 8, 9`, same as below

2023-03-07 12:04 UTC, peterlimg commented on code/go/0chain.net/smartcontract/storagesc/challenge.go
> +type TransactionData struct {
transaction is parsed at the beginning of executing the smart contract, see [code](https://github.com/0chain/0chain/blob/88ee6c96020bce2d9fd7eed1144c4f91e47df7ad/code/go/0chain.net/smartcontract/storagesc/challenge.go#L444). You can get all the txn data from the `ChallengeResponse`.

2023-03-07 12:04 UTC, peterlimg commented on code/go/0chain.net/smartcontract/storagesc/challenge.go
> +	balances cstate.StateContextI, options ...string) error {
Use `challengeID string` as param rather than optional params, there's no case that do not need the challenge id for blobber reward.

2023-03-07 12:04 UTC, peterlimg commented on code/go/0chain.net/smartcontract/storagesc/challenge.go
> +	blobAlloc *BlobberAllocation, validators []string, balances cstate.StateContextI, options ...string) (err error) {
Same as blobberReward

2023-03-07 12:04 UTC, peterlimg commented on code/go/0chain.net/smartcontract/storagesc/challenge.go
> +	err = json.Unmarshal([]byte(t.TransactionData), transactionData)
We can get the challeng id from `cab.challenge.ID`. Please do not parse the txn again, we should not parse the txn manually anywhere in the smart contract. It has been parsed at the beginning of the SC.

2023-03-07 12:04 UTC, peterlimg commented on code/go/0chain.net/smartcontract/storagesc/challenge.go
> +	transactionData := &TransactionData{}
Same as above

2023-03-07 12:04 UTC, peterlimg commented on code/go/0chain.net/smartcontract/storagesc/challengepool.go
> +	options ...string) (err error) {
Let's use `challengeID string` explicitly

2023-04-22 06:25 UTC, closed without merging