Optimize payFee
0chain/0chain pull request #2198
Opened 2023-03-07 07:29 UTC by peterlimg

## Fixes
- closes #2002
## Changes

## Need to be mentioned in CHANGELOG.md?

## Tests
Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/0chain/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

## Associated PRs (Link as appropriate):
- blobber:
- gosdk:
- system_test:
- zboxcli:
- zwalletcli:
- Other: ...

2023-03-07 10:51 UTC, dabasov requested changes
lgtm

2023-03-07 10:51 UTC, dabasov commented on code/go/0chain.net/smartcontract/minersc/delete.go
> +//func resetDeleteSharderIDs(state state.StateContextI) error {
clean up commented code

2023-03-07 10:51 UTC, dabasov approved these changes
lgtm

2023-03-08 05:36 UTC, service-0chain commented
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | TRUE  |
| system-tests  | master  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | optimize-pay-fees  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | master  |
| 0proxy  | staging  |
| 0search  | staging  |

2023-03-08 05:39 UTC, merged