Add new is available field to blobber
0chain/0chain pull request #2247
Opened 2023-03-28 09:41 UTC by Sriep

## Fixes

## Changes

## Need to be mentioned in CHANGELOG.md?

## Tests
Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/0chain/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

## Associated PRs (Link as appropriate):
- blobber:
- gosdk: https://github.com/0chain/gosdk/pull/866
- system_test:
- zboxcli: https://github.com/0chain/zboxcli/pull/398
- zwalletcli:
- Other: ...

2023-03-30 11:57 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | staging  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | blobber_available  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | master  |
| 0proxy  | staging  |
| 0search  | staging  |

2023-03-31 10:31 UTC, peterlimg requested changes
Just a few minor change requests

2023-03-31 10:31 UTC, peterlimg commented on code/go/0chain.net/smartcontract/storagesc/blobber.go
> +	logging.Logger.Info("piers updateBlobber end", zap.Any("blober", blobber))
Remove debug logging before merging

2023-03-31 10:31 UTC, peterlimg commented on code/go/0chain.net/smartcontract/storagesc/blobber.go
> +	logging.Logger.Info("piers updateBlobberSettings", zap.Any("update blobber", updatedBlobber))
Same as above

2023-03-31 10:31 UTC, peterlimg commented on code/go/0chain.net/smartcontract/storagesc/blobber_eventdb.go
> +	logging.Logger.Info("piers emitUpdateBlobber", zap.Any("data", data))
Same

2023-04-04 10:54 UTC, peterlimg approved these changes
LGTM

2023-04-04 10:54 UTC, merged