testing for flakines in bl-update
0chain/0chain pull request #2298
Opened 2023-04-15 18:39 UTC by mayank-2105

## Fixes

## Changes

## Need to be mentioned in CHANGELOG.md?

## Tests
Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/0chain/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

## Associated PRs (Link as appropriate):
- blobber:
- gosdk:
- system_test:
- zboxcli:
- zwalletcli:
- Other: ...

2023-04-17 14:43 UTC, Kishan-Dhakan requested changes

2023-04-17 14:43 UTC, Kishan-Dhakan commented on code/go/0chain.net/smartcontract/storagesc/handler.go
>  		err := common.NewErrInternal("missing blobber: " + blobberID)
Also return the actual error, no need to return this

2023-04-17 18:01 UTC, mayank-2105 commented on code/go/0chain.net/smartcontract/storagesc/handler.go
>  		err := common.NewErrInternal("missing blobber: " + blobberID)
Done in new commit. Please review and merge.

2023-04-18 06:55 UTC, peterlimg approved these changes
LGTM

2023-04-18 20:21 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | bl_update_testcase  |
| gosdk  | staging  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | test_bl_update  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

2023-04-19 16:32 UTC, service-0chain commented
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | bl_update_testcase  |
| gosdk  | staging  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | test_bl_update  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

2023-04-21 22:00 UTC, service-0chain commented
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | TRUE  |
| system-tests  | bl_update_testcase  |
| gosdk  | staging  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | test_bl_update  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

2023-04-21 22:05 UTC, Kishan-Dhakan approved these changes

2023-04-21 22:05 UTC, merged