Readme turning off fees
0chain/0chain pull request #2315
Opened 2023-04-19 13:24 UTC by Sriep

## Fixes

## Changes

## Need to be mentioned in CHANGELOG.md?

## Tests
Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/0chain/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

## Associated PRs (Link as appropriate):
- blobber:
- gosdk:
- system_test:
- zboxcli:
- zwalletcli:
- Other: ...

2023-04-20 10:42 UTC, peterlimg requested changes

2023-04-20 10:42 UTC, peterlimg commented on README.md
> +  1.5) If you want to turn off fees adjust `server_chain.smart_contract.mine` from `true` to `false`
Should be `miner`

2023-04-20 10:42 UTC, peterlimg commented on code/go/0chain.net/smartcontract/storagesc/README.md
> +the `server_chain.smart_contract.mine` setting in 0chain.yaml from `true` to `false`.
Same as above

2023-04-21 00:05 UTC, peterlimg approved these changes
LGTM

2023-04-21 07:01 UTC, service-0chain commented
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | staging  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | readme_fees  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

2023-04-21 07:09 UTC, merged