Feature: add "amount" for "burn" smart contract method
0chain/0chain pull request #2322
Opened 2023-04-23 16:45 UTC by YarikRevich

2023-04-24 09:47 UTC, dabasov requested changes

2023-04-24 09:47 UTC, dabasov commented on code/go/0chain.net/smartcontract/dbs/goose/migrations/001_events_db.sql
> +                              amount bigint,
add it to the different migration as an alter table

2023-04-24 13:26 UTC, YarikRevich commented on code/go/0chain.net/smartcontract/dbs/goose/migrations/001_events_db.sql
> +                              amount bigint,
Done

2023-04-25 13:27 UTC, dabasov approved these changes
lgtm

2023-04-25 19:17 UTC, service-0chain commented
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | TRUE  |
| system-tests  | master  |
| gosdk  | staging  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | feature/amount_field  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

2023-04-26 13:52 UTC, merged