2318 capture all the errors on transactions
0chain/0chain pull request #2324
Opened 2023-04-24 11:32 UTC by Jayashsatolia403

## Fixes

## Changes

## Need to be mentioned in CHANGELOG.md?

## Tests
Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/0chain/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

## Associated PRs (Link as appropriate):
- blobber:
- gosdk:
- system_test:
- zboxcli:
- zwalletcli:
- Other: ...

2023-04-27 04:26 UTC, peterlimg requested changes

2023-04-27 04:26 UTC, peterlimg commented on code/go/0chain.net/smartcontract/dbs/event/transaction.go
> +	// read all the transactions from the transaction table where status is 2 till last day
We are running this update every 60 seconds, so we don't need to get all from last day on every query, which could cause performance issue. So perhaps from last 2 minutes is enough.

2023-04-27 04:26 UTC, peterlimg commented on code/go/0chain.net/smartcontract/dbs/event/transaction.go
> +	logging.Logger.Info("jayashtransactionsLen", zap.Any("transactions", len(transactions)))
Clean up the logs before merging the PR, could be `logging.Logger.Info("update transaction errors, txn len"...)`.

2023-04-27 04:26 UTC, peterlimg commented on code/go/0chain.net/smartcontract/dbs/event/transaction.go
> +		logging.Logger.Info("jayashTransaction : ", zap.Any("transactions :", &TransactionErrors{
Clean up logs before merging

2023-04-27 04:26 UTC, peterlimg commented on code/go/0chain.net/smartcontract/storagesc/handler.go
> +		rest.MakeEndpoint(storage+"/transaction-errors", srh.getTransactionErrors),
Let's enable this in development mode only.

2023-04-28 20:52 UTC, dabasov requested changes

2023-04-28 20:52 UTC, dabasov commented on code/go/0chain.net/sharder/handler.go
> +	logging.Logger.Debug("jayash edb", zap.Any("edb", edb))
remove log

2023-04-28 20:52 UTC, dabasov commented on code/go/0chain.net/sharder/handler.go
> +	sc := GetSharderChain()
can be done in one line `GetSharderChain().Chain.GetEventDb()`

2023-04-28 20:52 UTC, dabasov commented on code/go/0chain.net/smartcontract/dbs/event/transaction.go
> +	rows, err := edb.Get().Model(&Transaction{}).Select("output_hash, transaction_output, transaction_type").Where("status = ? and created_at > ?", 2, lastDayString).Group("output_hash, transaction_outp
you can insert results of the query like
```sql
INSERT INTO transaction_errors (a, b, c)
SELECT (a, b, c) FROM transactions WHERE status =2 ...
```

2023-05-01 00:56 UTC, peterlimg approved these changes
lgtm

2023-05-03 12:57 UTC, dabasov approved these changes
LGTM

2023-05-05 07:01 UTC, merged