Remove some handlers from miners
0chain/0chain pull request #2379
Opened 2023-05-05 12:48 UTC by Sriep

## Fixes
This removes some of the handlers from miners. config, chain-state and chain-node. 
## Changes

## Need to be mentioned in CHANGELOG.md?

## Tests
Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/0chain/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

## Associated PRs (Link as appropriate):
- blobber:
- gosdk:
- system_test:
- zboxcli:
- zwalletcli:
- Other: ...

2023-05-05 16:44 UTC, stewartie4 reviewed
This may also need updated https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/chaincore/chain/handler.go#L109

2023-05-08 01:28 UTC, peterlimg commented
@Sriep we may keep handlers the following handlers on miners, they could be used to debug state and check config when needed:
- /v1/scstate/get
- /v1/config/get

2023-05-09 14:29 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | staging  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | trim_miner_handlers  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

2023-05-09 20:54 UTC, stewartie4 reviewed
Happy approve pending green test run (this is what caused me issues on my attempt at this issue!)

2023-05-10 15:47 UTC, dabasov commented
> @Sriep we may keep handlers the following handlers on miners, they could be used to debug state and check config when needed:
> 
> * /v1/scstate/get
> * /v1/config/get

what do you think of putting them under IsDevelopment check? @peterlimg

2023-05-11 01:25 UTC, peterlimg requested changes

2023-05-11 01:25 UTC, peterlimg commented on code/go/0chain.net/chaincore/chain/state_handler.go
> -	http.HandleFunc("/v1/scstate/get", common.WithCORS(common.UserRateLimit(common.ToJSONResponse(c.GetNodeFromSCState))))
This endpoint is required for both miners and sharders, but as @dabasov suggested, we can put it under `development` endpoints, so as the `config/get`.

2023-05-12 06:39 UTC, peterlimg requested changes

2023-05-12 06:39 UTC, peterlimg commented on code/go/0chain.net/chaincore/chain/handler.go
> +	m := map[string]func(http.ResponseWriter, *http.Request){
Sorry, I forget to mention that the endpoints of `/estimate_txn_fee` and `fees_table` endpoints are all miners endpoints, so as some other endpoints, such as `/get/latest_finalized` and `/latest_finalized_magic_block_summary`, etc. Basically all endpoints read data from MPT or data struct other than event db should be supported by both miners and sharders. We'd better keep them in common place of handlersMap and only move specific handlers to minerHandlerMap and sharderHandlersMap.

2023-05-17 06:05 UTC, peterlimg requested changes

2023-05-17 06:05 UTC, peterlimg commented on code/go/0chain.net/chaincore/chain/handler_integration_tests.go
> +		hMap := minerHandlersMap(c)
Should not create new `hMap` here, the hMap will be empty. So let's use `hMap = minerHandlersMap(c)` instead

2023-05-17 06:05 UTC, peterlimg commented on code/go/0chain.net/chaincore/chain/handler_integration_tests.go
> +		hMap := handlersMap(c)
Same as above

2023-05-17 08:51 UTC, service-0chain commented
Manual system tests [cancelled] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | staging  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | trim_miner_handlers  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

2023-05-17 16:54 UTC, service-0chain commented
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | staging  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | trim_miner_handlers  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

2023-05-20 06:46 UTC, peterlimg approved these changes
LGTM

2023-05-20 06:47 UTC, merged

2023-05-20 10:20 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | staging  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |