enhancing disk setup script
0chain/0chain pull request #2396
Opened 2023-05-10 11:54 UTC by shahnawaz-creator

## Fixes

## Changes

## Need to be mentioned in CHANGELOG.md?

## Tests
Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/0chain/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

## Associated PRs (Link as appropriate):
- blobber:
- gosdk:
- system_test:
- zboxcli:
- zwalletcli:
- Other: ...

2023-05-10 12:42 UTC, dabasov requested changes

2023-05-10 12:42 UTC, dabasov commented on docker.local/config/benchmark.yaml
> +    min_stakke: 0.0
what is it for?

2023-05-10 12:42 UTC, dabasov commented on docker.local/config/benchmark.yaml
> +    - "multi_sig"
don't need vesting and multi_sig

2023-05-10 12:42 UTC, dabasov commented on docker.local/config/benchmark.yaml
> +  time_unit: 1ms
why is it changed?

2023-05-10 13:01 UTC, shahnawaz-creator commented on docker.local/config/benchmark.yaml
> +    min_stakke: 0.0
changes reverted

2023-05-10 13:01 UTC, shahnawaz-creator commented on docker.local/config/benchmark.yaml
> +    - "multi_sig"
changes reverted

2023-05-10 13:02 UTC, shahnawaz-creator commented on docker.local/config/benchmark.yaml
> +  time_unit: 1ms
changes reverted

2023-05-10 13:12 UTC, dabasov approved these changes
lgtm

2023-06-02 19:39 UTC, shahnawaz-creator commented
Cron job added here --> https://github.com/0chain/0helm/pull/255

2023-06-02 19:39 UTC, closed without merging