WIP : Added new endpoint for the challenge rewards
0chain/0chain pull request #2440
Opened 2023-05-24 05:30 UTC by Jayashsatolia403

## Fixes

## Changes

## Need to be mentioned in CHANGELOG.md?

## Tests
Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/0chain/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

## Associated PRs (Link as appropriate):
- blobber:
- gosdk:
- system_test:
- zboxcli:
- zwalletcli:
- Other: ...

2023-05-29 11:04 UTC, dabasov requested changes

2023-05-29 11:04 UTC, dabasov commented on code/go/0chain.net/smartcontract/dbs/event/challenge.go
> +		Where("allocation_id = ? AND passed = ?", allocationID, true).
there is no index for `allocation_id` and `passed` this query will be slow

2023-05-29 11:04 UTC, dabasov commented on code/go/0chain.net/smartcontract/dbs/event/reward_provider_dev.go
> +	err := edb.Get().Table("reward_providers").Select("provider_id, reward_type,  sum(amount) as amount").Where("allocation_id = ? AND reward_type IN (?, ?)", allocationID, spenum.ValidationReward, spen
avoid using group in production

2023-05-29 11:04 UTC, dabasov commented on code/go/0chain.net/smartcontract/dbs/event/reward_provider_dev.go
> +		err = edb.Get().Table("reward_delegates").Select("pool_id as delegate_id, sum(amount) as amount").Where("provider_id = ? AND allocation_id = ? AND reward_type IN (?, ?)", rp.ProviderId, allocationI
same here

2023-05-29 11:04 UTC, dabasov commented on code/go/0chain.net/smartcontract/dbs/event/reward_provider_dev.go
> +	err := edb.Get().Table("reward_providers").Select("provider_id, sum(amount) as amount").Where("allocation_id = ? AND reward_type = ?", allocationID, spenum.FileDownloadReward).Group("provider_id, re
group is not allowed

2023-05-29 11:04 UTC, dabasov commented on code/go/0chain.net/smartcontract/dbs/event/reward_provider_dev.go
> +	err := edb.Get().Table("reward_providers").Select("provider_id, sum(amount) as amount").Where("allocation_id = ? AND reward_type = ?", allocationID, spenum.CancellationChargeReward).Group("provider_
same here

2023-05-29 11:04 UTC, dabasov commented on code/go/0chain.net/smartcontract/dbs/event/reward_provider_dev.go
> +		err = edb.Get().Table("reward_delegates").Select("pool_id as delegate_id, sum(amount) as amount").Where("provider_id = ? AND allocation_id = ? AND reward_type = ?", rp.ProviderId, allocationID, spe
same here

2023-05-29 11:04 UTC, dabasov commented on code/go/0chain.net/smartcontract/dbs/event/reward_provider_dev.go
> +	for _, rp := range rps {
you are running query for every element in the list, it will be slow

2023-05-29 11:04 UTC, dabasov commented on code/go/0chain.net/smartcontract/dbs/goose/migrations/001_events_db.sql
> +                                         allocation_id text
do not change in initial script, make different migration

2023-06-09 05:08 UTC, peterlimg requested changes, later dismissed

2023-06-09 05:08 UTC, peterlimg commented on code/go/0chain.net/smartcontract/dbs/types.go
> +	AllocationID string `json:"challenge_id"`
Please use the same json tag name, the challenge id is different from the allocation id

2023-06-09 05:08 UTC, peterlimg commented on code/go/0chain.net/smartcontract/storagesc/handler.go
> +		restEndpoints = append(restEndpoints, rest.MakeEndpoint(storage+"/acr", srh.getAllocationChallengeRewards))
let's use the same endpoint format, so could be `/allocation-challenge-rewards` or `/alloc-challenge-rewards` rather that the abbreviation of `/acr`.

2023-06-17 20:43 UTC, dabasov approved these changes
lgtm

2023-06-17 20:44 UTC, merged

2023-06-18 04:40 UTC, service-0chain commented
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | false  |
| system-tests  | master  |
| gosdk  | staging  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | fix/conductor-tests  |
| 0box  | staging  |
| 0dns  | staging  |