Fix allocation used storage
0chain/0chain pull request #2563
Opened 2023-06-29 10:30 UTC by Jayashsatolia403

## Fixes

## Changes

## Need to be mentioned in CHANGELOG.md?

## Tests
Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/0chain/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

## Associated PRs (Link as appropriate):
- blobber:
- gosdk:
- system_test:
- zboxcli:
- zwalletcli:
- Other: ...

2023-06-29 16:09 UTC, Kishan-Dhakan requested changes

2023-06-29 16:09 UTC, Kishan-Dhakan commented on code/go/0chain.net/smartcontract/dbs/event/allocation.go
> +	//	AddUpdate("write_pool", writePoolList, "allocations.write_pool - t.moved_to_challenge + t.moved_back").Exec(edb).Error
remove commented code

2023-06-29 20:58 UTC, dabasov commented on code/go/0chain.net/smartcontract/storagesc/allocation.go
> +	logging.Logger.Info("emitUpdateAllocationStatEvent", zap.Any("alloc", alloc))
do not use any please

2023-06-29 20:58 UTC, dabasov commented on code/go/0chain.net/smartcontract/storagesc/allocation.go
> -	if w.Size > 0 {
what was it for?

2023-06-29 20:58 UTC, dabasov commented on code/go/0chain.net/smartcontract/dbs/event/allocation.go
>  func withAllocStatsMerged() eventMergeMiddleware {
do we need this middleware?

2023-06-29 22:08 UTC, service-0chain commented
Manual system tests [cancelled] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | false  |
| system-tests  | sprint-june-5  |
| gosdk  | fix/alloc-size  |
| zboxcli  | sprint-june-5  |
| zwalletcli  | sprint-june-5  |
| 0chain  | fix/size  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

2023-06-29 22:45 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | false  |
| system-tests  | sprint-june-5  |
| gosdk  | sprint-june-5  |
| zboxcli  | sprint-june-5  |
| zwalletcli  | sprint-june-5  |
| 0chain  | fix/size  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

2023-06-30 07:42 UTC, service-0chain commented
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | false  |
| system-tests  | sprint-june-5  |
| gosdk  | sprint-june-5  |
| zboxcli  | sprint-june-5  |
| zwalletcli  | sprint-june-5  |
| 0chain  | fix/size  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

2023-06-30 09:07 UTC, service-0chain commented
Manual system tests [cancelled] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | false  |
| system-tests  | sprint-june-5  |
| gosdk  | sprint-june-5  |
| zboxcli  | fix/alloc-size  |
| zwalletcli  | sprint-june-5  |
| 0chain  | fix/size  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

2023-06-30 09:16 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | false  |
| system-tests  | sprint-june-5  |
| gosdk  | fix/alloc-size  |
| zboxcli  | fix/alloc-size  |
| zwalletcli  | sprint-june-5  |
| 0chain  | fix/size  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

2023-06-30 09:51 UTC, service-0chain commented
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | false  |
| system-tests  | sprint-june-5  |
| gosdk  | fix/alloc-size  |
| zboxcli  | fix/alloc-size  |
| zwalletcli  | sprint-june-5  |
| 0chain  | fix/size  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

2023-06-30 13:50 UTC, service-0chain commented
Manual system tests [cancelled] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | false  |
| system-tests  | sprint-june-5  |
| gosdk  | sprint-june-5  |
| zboxcli  | sprint-june-5  |
| zwalletcli  | sprint-june-5  |
| 0chain  | fix/size  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

2023-06-30 16:12 UTC, dabasov approved these changes
lgtm

2023-06-30 17:27 UTC, Kishan-Dhakan approved these changes

2023-06-30 17:27 UTC, merged