Fix finish Allocation
0chain/0chain pull request #2598
Opened 2023-07-07 14:00 UTC by Jayashsatolia403

## Fixes

## Changes

## Need to be mentioned in CHANGELOG.md?

## Tests
Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/0chain/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

## Associated PRs (Link as appropriate):
- blobber:
- gosdk:
- system_test:
- zboxcli:
- zwalletcli:
- Other: ...

2023-07-09 17:43 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | false  |
| system-tests  | sprint-july-1  |
| gosdk  | sprint-july-1  |
| zboxcli  | sprint-july-1  |
| zwalletcli  | sprint-july-1  |
| 0chain  | fix/finishAllocation  |
| blobber  | sprint-july-1  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

2023-07-10 20:12 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | false  |
| system-tests  |   |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  |   |
| zwalletcli  |   |
| 0chain  | sprint-july-1  |
| blobber  |   |
| authorizer  |   |
| 0box  |   |
| 0dns  |   |

2023-07-12 14:19 UTC, dabasov commented on .github/workflows/benchmark-test.yml
> +concurrency:
do we need these changes?

2023-07-12 14:19 UTC, dabasov commented on .github/workflows/build-&-publish-docker-image.yml
> +    branches: [ master, staging, sprint* ]
do we need to change this file

2023-07-12 14:19 UTC, dabasov commented on .github/workflows/system_tests.yml
> +       repo_snapshots_branch:
and this one

2023-07-13 18:38 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | false  |
| system-tests  |   |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  |   |
| zwalletcli  |   |
| 0chain  | sprint-july-2  |
| blobber  |   |
| authorizer  |   |
| 0box  |   |
| 0dns  |   |

2023-07-16 23:08 UTC, service-0chain commented
Manual system tests [cancelled] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | false  |
| system-tests  |   |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  |   |
| zwalletcli  |   |
| 0chain  | fix/finishAllocation  |
| blobber  |   |
| authorizer  |   |
| 0box  |   |
| 0dns  |   |

2023-07-17 00:18 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | false  |
| system-tests  |   |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  |   |
| zwalletcli  |   |
| 0chain  | fix/finishAllocation  |
| blobber  |   |
| authorizer  |   |
| 0box  |   |
| 0dns  |   |

2023-07-17 11:01 UTC, dabasov requested changes

2023-07-17 11:01 UTC, dabasov commented on code/go/0chain.net/smartcontract/storagesc/allocation.go
> +	emitUpdateAllocationAndBlobberStats(alloc, balances)
can we emit it higher the stack where `finalizedPassRates` is called?

2023-07-17 11:01 UTC, dabasov commented on code/go/0chain.net/smartcontract/storagesc/allocation.go
> +	emitUpdateAllocationAndBlobberStats(alloc, balances)
also maybe we can call it higher the stack

2023-07-17 11:01 UTC, dabasov commented on code/go/0chain.net/smartcontract/storagesc/allocation.go
> +			ratio := float64(d.Stats.UsedSize) / (float64(alloc.Stats.UsedSize) * float64(alloc.DataShards+alloc.ParityShards) / float64(alloc.DataShards))
can you please break it into 2 different ratios and then multiply them?

2023-07-17 11:30 UTC, Jayashsatolia403 commented on code/go/0chain.net/smartcontract/storagesc/allocation.go
> +	emitUpdateAllocationAndBlobberStats(alloc, balances)
Not sure why do we want to do this. Can you please explain?

2023-07-18 15:01 UTC, dabasov approved these changes
lgtm

2023-07-18 15:01 UTC, merged