Fix/repace blobber
0chain/0chain pull request #2654
Opened 2023-07-27 12:15 UTC by Jayashsatolia403

## Fixes

## Changes

## Need to be mentioned in CHANGELOG.md?

## Tests
Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/0chain/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

## Associated PRs (Link as appropriate):
- blobber:
- gosdk:
- system_test:
- zboxcli:
- zwalletcli:
- Other: ...

2023-07-28 16:53 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | false  |
| system-tests  |   |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  |   |
| zwalletcli  |   |
| 0chain  | fix/repace-blobber  |
| blobber  |   |
| authorizer  |   |
| 0box  |   |
| 0dns  |   |

2023-07-28 20:14 UTC, service-0chain commented
Manual system tests [cancelled] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | false  |
| system-tests  |   |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  |   |
| zwalletcli  |   |
| 0chain  | fix/repace-blobber  |
| blobber  |   |
| authorizer  |   |
| 0box  |   |
| 0dns  |   |

2023-07-29 14:08 UTC, dabasov commented on code/go/0chain.net/smartcontract/storagesc/allocation.go
> +			ba.Stats.SuccessChallenges += ba.Stats.OpenChallenges
why do we add to successful challenges count?

2023-07-31 13:54 UTC, dabasov requested changes

2023-07-31 13:54 UTC, dabasov commented on code/go/0chain.net/smartcontract/dbs/event/blobber.go
> +		b, err := edb.GetBlobber(id)
it will generate n queries instead of single one, why do you need this change? you need to use array-like approach here we use in updater for example

2023-07-31 14:24 UTC, dabasov requested changes

2023-07-31 14:24 UTC, dabasov commented on code/go/0chain.net/smartcontract/dbs/goose/migrations/001_events_db.sql
> -                                                 min_lock_demand numeric,
do not change 1-st script

2023-07-31 14:24 UTC, dabasov commented on code/go/0chain.net/smartcontract/storagesc/models.go
> +			sa.BlobberAllocs[i] = nil
delete element from the list

2023-07-31 14:24 UTC, dabasov commented on code/go/0chain.net/smartcontract/storagesc/models.go
> +			blobbers[i] = nil
ifyou want to delete it from the list, simplydelete it

2023-07-31 14:24 UTC, dabasov commented on code/go/0chain.net/smartcontract/storagesc/models.go
>  	if _, err := balances.InsertTrieNode(removedBlobber.GetKey(), removedBlobber); err != nil {
why removeAllocationFromBlobber() is removed from here?

2023-07-31 14:24 UTC, dabasov commented on code/go/0chain.net/smartcontract/storagesc/models.go
> +			sa.BlobberAllocs[i] = nil
how do we update this delete in vents_db?

2023-07-31 15:42 UTC, dabasov approved these changes
merge when fixed

2023-07-31 19:31 UTC, merged

2023-07-31 19:54 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | false  |
| system-tests  |   |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  |   |
| zwalletcli  |   |
| 0chain  | sprint-july-4  |
| blobber  |   |
| authorizer  |   |
| 0box  |   |
| 0dns  |   |

2023-08-01 19:02 UTC, dabasov reviewed
lgtm