Feature/ Challenge based on rounds
0chain/0chain pull request #2741
Opened 2023-08-26 07:04 UTC by Jayashsatolia403

## Fixes

## Changes

## Need to be mentioned in CHANGELOG.md?

## Tests
Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/0chain/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

## Associated PRs (Link as appropriate):
- blobber:
- gosdk:
- system_test:
- zboxcli:
- zwalletcli:
- Other: ...

2023-09-04 20:13 UTC, dabasov requested changes

2023-09-04 20:13 UTC, dabasov commented on code/go/0chain.net/smartcontract/storagesc/challengepool.go
> +	case err == nil:
nil is good

2023-09-04 20:13 UTC, dabasov commented on code/go/0chain.net/smartcontract/storagesc/challengepool.go
> +	switch {
empty switch is not good, you better break it in ifs

2023-09-09 15:19 UTC, dabasov approved these changes
lgtm

2023-09-14 19:30 UTC, dabasov commented on code/go/0chain.net/smartcontract/stakepool/edb_stakepool.go
> +		logging.Logger.Info("EmitStakePoolBalanceUpdate", zap.Any("dpu", dpu))
remove log please or change level to debug

2023-09-14 19:30 UTC, dabasov commented on code/go/0chain.net/smartcontract/storagesc/allocation.go
> +		} else {
if ErrorNotFound return it unchanged

2023-09-14 19:30 UTC, dabasov commented on code/go/0chain.net/smartcontract/storagesc/allocation.go
> +	logging.Logger.Info("Jayash Updating allocation to DB",
remove logging

2023-09-15 17:31 UTC, dabasov reviewed
c

2023-09-15 18:18 UTC, merged

2023-09-15 19:26 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | false  |
| system-tests  |   |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  |   |
| zwalletcli  |   |
| 0chain  | sprint-1.11  |
| blobber  |   |
| authorizer  |   |
| 0box  |   |
| 0dns  |   |