Fix Challenge Stats
0chain/0chain pull request #2801
Opened 2023-09-24 23:26 UTC by Jayashsatolia403

## Fixes

## Changes

## Need to be mentioned in CHANGELOG.md?

## Tests
Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/0chain/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

## Associated PRs (Link as appropriate):
- blobber:
- gosdk:
- system_test:
- zboxcli:
- zwalletcli:
- Other: ...

2023-09-30 11:25 UTC, dabasov requested changes

2023-09-30 11:25 UTC, dabasov commented on code/go/0chain.net/core/maths/maths.go
> +func ConvertToUint64(a int64) (int64, error) {
you can't change it, it is different function then

2023-09-30 11:25 UTC, dabasov commented on code/go/0chain.net/core/maths/maths.go
> +func ConvertInt64sToUint64s(numbers ...int64) ([]int64, error) {
create different function

2023-09-30 11:25 UTC, dabasov commented on code/go/0chain.net/smartcontract/dbs/event/blobber.go
> +func mergeAddChallengesToBlobberEvents() *eventsMergerImpl[ChallengeStatsDeltas] {
why did you remove the builder?

2023-09-30 11:25 UTC, dabasov commented on code/go/0chain.net/smartcontract/dbs/event/blobber.go
> +func sqlUpdateOpenChallenges(deltas []ChallengeStatsDeltas) string {
use builder here, do not use raw queries

2023-09-30 11:25 UTC, dabasov commented on code/go/0chain.net/smartcontract/dbs/event/blobber.go
> +func sqlUpdateBlobberChallenges(deltas []ChallengeStatsDeltas) string {
use builder here, you can't use custom queries

2023-09-30 20:15 UTC, Jayashsatolia403 commented
Closed accidently. Really sorry for inconvenience.

2023-10-01 11:15 UTC, dabasov approved these changes
lgtm

2023-10-01 11:17 UTC, merged