Fix stake pool max num delegates
0chain/0chain pull request #3066
Opened 2023-12-31 19:26 UTC by Jayashsatolia403

## Fixes

## Changes

## Need to be mentioned in CHANGELOG.md?

## Tests
Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/0chain/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

## Associated PRs (Link as appropriate):
- blobber:
- gosdk:
- system_test:
- zboxcli:
- zwalletcli:
- Other: ...

2024-01-01 07:14 UTC, peterlimg approved these changes
LGTM

2024-01-03 09:08 UTC, dabasov requested changes

2024-01-03 09:08 UTC, dabasov commented on code/go/0chain.net/smartcontract/minersc/delegate_pools.go
> +	if err := mn.save(balances); err != nil {
you can't save in get method

2024-01-03 09:31 UTC, Jayashsatolia403 commented on code/go/0chain.net/smartcontract/minersc/delegate_pools.go
> +	if err := mn.save(balances); err != nil {
Accidentally added it. Fixed.

2024-01-12 15:08 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | false  |
| system-tests  |   |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  |   |
| zwalletcli  |   |
| 0chain  | fix/max-delegates  |
| blobber  |   |
| authorizer  |   |
| 0box  |   |
| 0dns  |   |

2024-01-21 16:40 UTC, dabasov approved these changes
lgtm

2024-01-21 16:40 UTC, merged