added UTs to assert blobber and allocation stats
0chain/0chain pull request #3196
Opened 2024-03-17 12:26 UTC by Zorro30

## Fixes

## Changes

## Need to be mentioned in CHANGELOG.md?

## Tests
Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/0chain/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

## Associated PRs (Link as appropriate):
- blobber:
- gosdk:
- system_test:
- zboxcli:
- zwalletcli:
- Other: ...

2024-03-20 19:26 UTC, Jayashsatolia403 requested changes

2024-03-20 19:26 UTC, Jayashsatolia403 commented on code/go/0chain.net/smartcontract/storagesc/blobber_test.go
> +		require.Greater(t, blobAfterWrite.SavedData, savedDataBeforeUpdate)
Please assert with exact values.

2024-03-25 18:36 UTC, Jayashsatolia403 approved these changes
lgtm

2024-03-26 21:00 UTC, dabasov approved these changes
lgtm

2024-03-27 15:02 UTC, merged