Unit test doc
0chain/0chain pull request #325
Opened 2021-05-31 09:45 UTC by Sriep

Document about writing unit tests.

2021-05-31 18:56 UTC, shravanshetty1 requested changes

2021-05-31 18:56 UTC, shravanshetty1 commented on docs/unit-tests.md
> +[0chain\generate_mcoks.sh](https://github.com/0chain/0chain/blob/master/generate_mocks.sh) script.
typo

2021-06-06 20:41 UTC, Dmdv commented
@Sriep Do we use Ginkgo and gomock or it is not encouraged?

2021-06-06 20:50 UTC, Dmdv commented
@Sriep   
I found no mentions about a convention where to keep all test factory code.  
Imagine not interfaces but types which are not generated by **mockery**.  
Some use-test cases are repetitive throughout the same category tests and factory for said types are definitely worth keeping in the separate directory rather than being kept in a single file.

Keeping all test types factories make the code clumpy

2021-06-07 13:44 UTC, Sriep commented
```
Do we use Ginkgo and gomock or it is not encouraged?
```
Don't use Ginko or gomock unless we decide to use gomock or Ginkgo.

2021-06-07 13:54 UTC, Sriep commented
```
I found no mentions about a convention where to keep all test factory code.
```
How do you mean `test factory code?` We want to keep tests decoupled where possible. 

Some common functions maybe, but we want to avoid a large amount of common setup code 
that is not necessary for any particular test.

2021-06-08 10:31 UTC, Dmdv commented
> ```
> I found no mentions about a convention where to keep all test factory code.
> ```
> 
> How do you mean `test factory code?` Keep tests decoupled where possible. Also, try to avoid a large amount of common setup code that is not necessary for any particular test.

@Sriep 
Do you mean keeping all tests outside of the package folder in the test folder or keeping all tests alongside the tested files?

As for test factory code, I mean some common types created in different tests with copy-pasting. 
Do we place them in a separate folder?

2021-06-09 14:39 UTC, Sriep commented
For common methods and objects just be sensible. A common help _test file is fine.

2021-06-28 12:02 UTC, merged