Lint fixes for sprint 1.15
0chain/0chain pull request #3275
Opened 2024-05-16 16:11 UTC by Ash-KODES

## Fixes

## Changes

## Need to be mentioned in CHANGELOG.md?

## Tests
Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/0chain/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

## Associated PRs (Link as appropriate):
- blobber:
- gosdk:
- system_test:
- zboxcli:
- zwalletcli:
- Other: ...

2024-05-22 12:40 UTC, Jayashsatolia403 requested changes

2024-05-22 12:40 UTC, Jayashsatolia403 commented on code/go/0chain.net/chaincore/chain/config.go
> +		if err != nil {
Remove error check from here

2024-05-22 12:40 UTC, Jayashsatolia403 commented on code/go/0chain.net/smartcontract/storagesc/benchmark_setup.go
> +	//const mockWriePoolSize = 600000000 // Lint issue - Unused variable
Add unused lint ignore

2024-05-22 12:40 UTC, Jayashsatolia403 commented on code/go/0chain.net/smartcontract/storagesc/handler.go
> +		return nil, fmt.Errorf("not enough blobbers to honor the allocation: %d < %d", len(blobberIDs), numberOfBlobbers)
Don't modify error statement. You are missing a space here.

2024-05-22 12:40 UTC, Jayashsatolia403 commented on code/go/0chain.net/smartcontract/storagesc/models.go
> +							_ = fmt.Errorf("could not get challenge pool of alloc: %s, err: %v", sa.ID, e)
Add the error check with hardfork activator athena.

2024-05-22 12:40 UTC, Jayashsatolia403 commented on code/go/0chain.net/smartcontract/storagesc/stakepool.go
> +	sp, _ := getStakePool(providerType, providerID, balances)
Add error check with athena.

2024-05-31 15:55 UTC, Ash-KODES commented on code/go/0chain.net/smartcontract/storagesc/models.go
> +							_ = fmt.Errorf("could not get challenge pool of alloc: %s, err: %v", sa.ID, e)
This is already wrapped under apollo activator , do I need to do nesting with athena activator for error coming from `getChallengePool` ?

2024-06-14 10:29 UTC, Jayashsatolia403 requested changes

2024-06-14 10:29 UTC, Jayashsatolia403 commented on code/go/0chain.net/smartcontract/storagesc/challenge.go
> +		var blobbersSelected []ChallengeReadyBlobber
Revert this change.

2024-06-14 10:29 UTC, Jayashsatolia403 commented on code/go/0chain.net/smartcontract/storagesc/models.go
> +						demeterActError := cstate.WithActivation(balances, "demeter", func() (e error) { return },
Why is before function empty? We need to add older changes in before function as it is and add new changes in after function.

2024-06-14 10:29 UTC, Jayashsatolia403 commented on code/go/0chain.net/smartcontract/storagesc/stakepool.go
> +	var sp *stakePool
Add older code in before function.

2024-06-24 14:28 UTC, merged