Hotfix validator partition
0chain/0chain pull request #3344
Opened 2024-07-27 22:22 UTC by Jayashsatolia403

## Fixes

## Changes

## Need to be mentioned in CHANGELOG.md?

## Tests
Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/0chain/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

## Associated PRs (Link as appropriate):
- blobber:
- gosdk:
- system_test:
- zboxcli:
- zwalletcli:
- Other: ...

2024-07-28 09:03 UTC, dabasov requested changes

2024-07-28 09:03 UTC, dabasov commented on code/go/0chain.net/smartcontract/partitions/partitions.go
> +	for i := 0; i <= p.Last.Loc; i++ {
we should not save loc for last partition, it should be  `i < p.Last.Loc`

2024-07-29 14:33 UTC, dabasov requested changes

2024-07-29 14:33 UTC, dabasov commented on code/go/0chain.net/smartcontract/storagesc/sc.go
> -		actErr = chainstate.WithActivation(balances, "artemis", func() error {
it can cause the error when we will replay the transactons

2024-07-29 14:33 UTC, dabasov commented on code/go/0chain.net/smartcontract/partitions/partitions.go
> +func (p *Partitions) RepairValidatorPartitions(balances state.StateContextI) error {
can we make it generic for all the partitions? we can pass the name of partitions and load from MPT by name

2024-07-29 15:00 UTC, Jayashsatolia403 commented on code/go/0chain.net/smartcontract/storagesc/sc.go
> -		actErr = chainstate.WithActivation(balances, "artemis", func() error {
As discussed we are dropping all activator code before demeter. Should I revert it back?

2024-07-29 15:42 UTC, dabasov approved these changes
lgtm

2024-07-29 15:53 UTC, merged