Features/allocation transfer 333
0chain/0chain pull request #345
Opened 2021-06-06 03:44 UTC by andrenerd

Add method to transfer allocation from one owner to another.
The flow:
- update allocation owner's write pool to transfer non-used tokens from the related allocation pools
- update and save several allocation fields

PS. related to allocation challenge pools are owner-independent and remain unchanged

2021-06-08 10:39 UTC, Sriep reviewed
Will review again when the unit tests are done.

2021-06-08 10:39 UTC, Sriep commented on code/go/0chain.net/smartcontract/storagesc/allocation.go
> +	err = sc.saveAllocation(alloc, balances)
Why not 
```go
return sc.saveAllocation(alloc, balances)
```
?

2021-06-08 10:39 UTC, Sriep commented on code/go/0chain.net/smartcontract/storagesc/writepool.go
> +
If you want to refactor here, remove the commented out code.

2021-06-08 10:39 UTC, Sriep commented on code/go/0chain.net/smartcontract/storagesc/writepool.go
> +func (ssc *StorageSmartContract) transferWritePool(t *transaction.Transaction,
Needs a unit test.

2021-06-08 10:39 UTC, Sriep commented on code/go/0chain.net/smartcontract/storagesc/allocation.go
> +) (resp string, err error) {
Needs a unit test.

2021-06-08 10:40 UTC, Sriep requested changes
Needs unit tests.

2021-06-12 23:20 UTC, guruhubb commented
@andrenerd @Sriep check my related comments 
https://github.com/0chain/zboxcli/issues/29#issuecomment-860120687

2021-06-28 13:13 UTC, Sriep commented
Replaced with curator transfer https://github.com/0chain/0chain/pull/366

2021-06-28 13:13 UTC, closed without merging