Test correct handling of MultiPutNode during pruning
0chain/0chain pull request #439
Opened 2021-08-01 16:20 UTC by rrrooommmaaa

This failing test shows that error in UpdateVersion() may lead to deletion of nodes

2021-08-05 11:55 UTC, Sriep commented
When I tested locally the chain kept getting stuck before round 20. Suggest should be manually integration tested again.

2021-08-05 12:51 UTC, Sriep requested changes
When I tested locally the chain kept getting stuck before round 20.

2021-08-05 14:13 UTC, rrrooommmaaa commented
I have merged changes from `master`, now the chain is moving fast.
Please merge.

2021-08-06 08:33 UTC, Sriep approved these changes

2021-08-06 08:33 UTC, merged