Add Partitions package and league tables
0chain/0chain pull request #547
Opened 2021-10-03 13:12 UTC by Sriep

Adds a new partitions package, and implements a league table to be used for block rewards.

League tables hold N divisions of M members order by a numeric field.
* `Add` adds a new member to the league.
* `Remove` removes a member
* `Change` changes the numeric field for an existing member

For a total number of T members, these operations are of order(SqareRoot(T)). This assumes the league is split into SquareRoot(T) divisions of maximum size SquareRoot(T).

Each time a member of the league table is moved a callback function is triggered. This can do stuff, like pay block rewards.

To see how it works check out the [fuzzy test](https://github.com/0chain/0chain/blob/49cc4533d1fe5571175e8bfb98de3504fb99ffdb/code/go/0chain.net/smartcontract/partitions/league_table_test.go#L131)

2021-10-07 04:21 UTC, peterlimg requested changes
Also, please comment all exported public methods and functions.

2021-10-07 04:21 UTC, peterlimg commented on code/go/0chain.net/smartcontract/partitions/league_table.go
> +func (lm leagueMember) GraterThan(item PartitionItem) bool {
Typo `GraterThan`

2021-10-07 04:21 UTC, peterlimg commented on code/go/0chain.net/smartcontract/partitions/league_table.go
> +// by promoting frmo a lower division
Typo `frmo`

2021-10-07 04:21 UTC, peterlimg commented on code/go/0chain.net/smartcontract/partitions/league_table.go
> +	lm, ok := opi.(leagueMember)
If the `OrderedPartitionItem` should always be `leagueMember`, maybe we can just pass the param in type of `leagueMember`.

2021-10-07 04:21 UTC, peterlimg commented on code/go/0chain.net/smartcontract/partitions/league_table.go
> +	lm2, ok := item.(leagueMember)
Add a method to `PartionItem` to get value and compare with the `leagueMember`'s value should be better, or we can just pass the `leagureMember` type of `item` instead of an interface.

2021-10-07 04:21 UTC, peterlimg commented on code/go/0chain.net/smartcontract/partitions/league_table.go
> +	lt.Divisions[targetDivision].changed = true
Dup `changed` updating.

2021-10-07 04:21 UTC, peterlimg commented on code/go/0chain.net/smartcontract/partitions/league_table.go
> +		return err
The error is nil, return a specific error or just nil maybe

2021-10-07 04:21 UTC, peterlimg commented on code/go/0chain.net/smartcontract/partitions/league_table.go
> +		return err
nil error

2021-10-07 04:21 UTC, peterlimg commented on code/go/0chain.net/smartcontract/partitions/league_table.go
> +	}
`i >= len(lt.Divisions)` is actually the same thing, index out of boundary.

2021-10-07 16:35 UTC, Sriep commented on code/go/0chain.net/smartcontract/partitions/league_table.go
> +	}
Yes but i don't want `i == len(lt.Divisions)` to be an error. So I just return a nil for the value. Maybe I should create a new division and return that.

2021-10-07 16:38 UTC, Sriep commented on code/go/0chain.net/smartcontract/partitions/league_table.go
> +	lm2, ok := item.(leagueMember)
I would then have to commit to a type, int, int64, state.Balance, float64 etc. Leave open for the moment.

2021-10-25 11:23 UTC, Sriep commented
Closing this as replaced with https://github.com/0chain/0chain/pull/588.

2021-10-25 11:23 UTC, closed without merging