Fix #925 added last viewed readmarker
0chain/0chain pull request #964
Opened 2022-02-02 00:08 UTC by samtholiya

Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/0chain/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master BEFORE merging this PR  
  
Associated PRs (Link as appropriate):
...

2022-02-04 00:22 UTC, samtholiya commented
![image](https://user-images.githubusercontent.com/11261548/152451297-df55fb48-1acb-485a-b006-555ddb993614.png)

manually inserted record to write marker for API...

2022-02-10 23:37 UTC, samtholiya commented
![image](https://user-images.githubusercontent.com/11261548/153515118-1d95a089-35db-472f-88d0-5543593f6c1c.png)

2022-02-10 23:38 UTC, samtholiya commented
![image](https://user-images.githubusercontent.com/11261548/153515175-90274b1b-faaa-43ef-a8bb-f1fae0abd3dd.png)

2022-02-11 14:30 UTC, ssardana08 requested changes

2022-02-11 14:30 UTC, ssardana96 commented on code/go/0chain.net/smartcontract/dbs/event/writemarker.go
> +	return wm, edb.Get().Debug().Model(&WriteMarker{}).Offset(offset).Limit(limit).Order(clause.OrderByColumn{
Why is Debug here?

2022-02-11 14:30 UTC, ssardana08 commented on code/go/0chain.net/smartcontract/dbs/event/writemarker.go
> +func (edb *EventDb) GetLatestWriteMarker() (WriteMarker, error) {
is this getting used anywhere?

2022-02-11 14:38 UTC, ssardana96 commented
looks good. just couple of comments
Please discuss with @chauchausoup @shaktals on its integration.

2022-02-11 17:13 UTC, shaktals commented
My opinion was that we did not need a specific API to get the last write or read marker, but just the possibility to order by timestamp and limit rows. Anyways, now that it is done, looks good to me.

2022-02-11 20:40 UTC, samtholiya commented on code/go/0chain.net/smartcontract/dbs/event/writemarker.go
> +func (edb *EventDb) GetLatestWriteMarker() (WriteMarker, error) {
done

2022-02-11 20:40 UTC, samtholiya commented on code/go/0chain.net/smartcontract/dbs/event/writemarker.go
> +	return wm, edb.Get().Debug().Model(&WriteMarker{}).Offset(offset).Limit(limit).Order(clause.OrderByColumn{
done

2022-02-11 20:42 UTC, samtholiya commented
@shaktals yes it is a general API delete the old comment to avoid confusion

2022-02-14 14:21 UTC, merged