Migrate to redis
0chain/0chain pull request #970
Opened 2022-02-04 06:55 UTC by jkrus

Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/0chain/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master BEFORE merging this PR  
  
Associated PRs (Link as appropriate):
...

2022-02-04 09:15 UTC, moldis commented on code/go/0chain.net/sharder/blockstore/store.go
> +		InitMetaRecordDB("localhost", "6379", "", true) //Removes existing metadata and creates new db
@jkrus you need to fetch configs from yaml file, just like everything else do

2022-02-04 09:16 UTC, moldis commented on code/go/0chain.net/sharder/blockstore/db.go
> +	/*bwrDB    *bbolt.DB
Please, clean up all comments. Merged code should be clean

2022-02-04 09:17 UTC, moldis requested changes
- Added few comments
- Need to update docker-compose to add Redis engine, otherwise after merging whole chain will fail

2022-02-04 10:34 UTC, lpoli commented on code/go/0chain.net/go.mod
> +	github.com/alicebob/miniredis v2.5.0+incompatible
This is not required. Line 8 is sufficient

2022-02-04 10:39 UTC, lpoli commented on code/go/0chain.net/sharder/blockstore/db.go
> +	return bwrRedis.SetToSorted(redisSortedSetUnmovedBlock, float64(ubr.CreatedAt.UnixMicro()), ubr.Hash)
`UnixMicro` is undefined in linux system. 
Generic function is required.
Should build this code with GOOS=linux.

2022-02-04 13:50 UTC, lpoli commented on code/go/0chain.net/sharder/blockstore/interface.go
> +	return &db
This instance has no full implementation of `blockStorage` interface

2022-02-04 13:51 UTC, lpoli commented on code/go/0chain.net/sharder/blockstore/interface.go
> +	blockStorage interface {
Its better to name interface as `blockStorageI` or `blockStorager` rather than `blockStorage`

2022-02-04 13:54 UTC, lpoli commented on code/go/0chain.net/sharder/blockstore/interface.go
> +		Addr:     "localhost:6379",
as @moldis pointer this use of `localhost:6379` it should not be hardcoded. It should be taken from config file. You can have input in `newBwrDB(addr , password string, db int, deleteExistingDB bool)` function

2022-02-04 14:05 UTC, lpoli requested changes
The work looks good and concise. However you need to run the 0chain in local and see if it is running fine.
Also check for library inconsistencies. `UnixMicro` is not available for linux.
Remove unused functions and also delete lines related to boltdb instead of commenting it out.

2022-02-04 14:05 UTC, lpoli commented on code/go/0chain.net/sharder/blockstore/interface.go
> +func newBlockStore(deleteExistingDB bool) {
This function is not used anywhere at all. I see that you've used `InitMetaRecordDB` function to initialize db. Please remove unused functions. It better to use `golangci-lint` with `unused`, `deadcode`,etc linters.

2022-02-11 23:58 UTC, peterlimg commented
https://github.com/0chain/0chain/issues/739#issuecomment-1036800013

2022-02-14 22:15 UTC, peterlimg commented
The boltDB is not being used actually, or do we have any plan to use it?

2022-03-29 13:44 UTC, lpoli requested changes
Please check for the existing redis-client and use it.

2022-03-29 13:44 UTC, lpoli commented on code/go/0chain.net/sharder/blockstore/store.go
> +		hostRedisDB, portRedisDB, passwordRedisDB = DefaultHostRedisDB, DefaultPortRedisDB, DefaultPasswordRedisDB
We should take these values from 0chain.yaml file. Please check for .yaml file and config and load using viper.
Since we can use already existing redis-client, we don't have to have it either.

2022-03-29 13:44 UTC, lpoli commented on code/go/0chain.net/sharder/blockstore/db.go
> +	"github.com/go-redis/redis"
There is already another redis client being used. Please use that same client. You can use of different client below.

https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/core/memorystore/connection.go#L13
https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/core/memorystore/pool.go#L11

2022-03-29 13:44 UTC, lpoli commented on code/go/0chain.net/sharder/blockstore/db.go
> +		_, _ = redisClient.FlushDB().Result()
If any error is there we can simply not start sharder. Let's not ignore error here.

2022-03-29 13:44 UTC, lpoli commented on code/go/0chain.net/sharder/blockstore/db.go
> +	redisClient = redis.NewClient(&redis.Options{
So if already existing redis-client is used then we don't need to have or initialize redis-client

2022-03-29 13:44 UTC, lpoli commented on code/go/0chain.net/sharder/blockstore/worker.go
> +			endTime := time.Date(
Why do we have create `endTime` this way?

2022-05-31 01:38 UTC, peterlimg commented
We'll use rocksdb, so should not work on this.

2022-05-31 01:38 UTC, closed without merging